# Generated by Django 5.2.9 on 2026-06-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_segmento_portal'),
        ('portal', '0002_rol_profesor_aprende'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalusuario',
            options={'verbose_name': 'Usuario portal clientes', 'verbose_name_plural': 'Usuarios portal clientes'},
        ),
        migrations.AlterField(
            model_name='portalusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador (portal clientes)'), ('profesor', 'Profesor (solo aula web /aprende/)'), ('viewer', 'Solo lectura (portal clientes)')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='SegmentoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('reenganche', 'Sin alcanzar módulo'), ('inactivos', 'Inactivos N días')], default='reenganche', max_length=20)),
                ('modulo_objetivo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dias_inactivo', models.PositiveSmallIntegerField(default=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupoestudiantes')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos_portal', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Segmento portal',
                'verbose_name_plural': 'Segmentos portal',
                'ordering': ['nombre'],
            },
        ),
    ]
