# Generated by Django 5.2.9 on 2026-06-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_segmento_portal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentoPortal',
        ),
    ]
