# Generated by Django 5.2.9 on 2026-06-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_portal_feedback_gei_factores'),
        ('portal', '0004_remove_segmento_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('bug', 'Problema / error'), ('mejora', 'Sugerencia de mejora'), ('pregunta', 'Pregunta'), ('otro', 'Otro')], default='mejora', max_length=20)),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_portal', to='core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback portal',
                'verbose_name_plural': 'Feedbacks portal',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PortalSugerenciaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('curso', 'Curso / facilitadora'), ('gei', 'Inventario GEI')], max_length=10)),
                ('pregunta', models.TextField(help_text='Pregunta o tema que la IA debería saber responder.')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_ia_portal', to='core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia IA portal',
                'verbose_name_plural': 'Sugerencias IA portal',
                'ordering': ['-creado'],
            },
        ),
    ]
