# Generated by Django 5.2.9 on 2026-07-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_portal_feedback_gei_factores'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalusuario',
            name='debe_cambiar_credenciales',
            field=models.BooleanField(default=False, help_text='Si está activo, al entrar al portal debe definir nombre y contraseña nueva.', verbose_name='Debe cambiar nombre y contraseña'),
        ),
        migrations.AddField(
            model_name='portalusuario',
            name='password_temporal',
            field=models.CharField(blank=True, default='', help_text='Solo para entrega al cliente. Se borra cuando el usuario completa el primer acceso. No es un hash: úsala solo como referencia operativa.', max_length=128, verbose_name='Contraseña temporal (visible)'),
        ),
    ]
