# Generated by Django 5.2.9 on 2026-07-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_cupos_portal_primer_acceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorAula',
            fields=[
            ],
            options={
                'verbose_name': 'Profesor aula',
                'verbose_name_plural': 'Profesores aula',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.portalusuario',),
        ),
    ]
