# Generated by Django 5.2.9 on 2025-12-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='cuerpo',
            new_name='cuerpo_mensaje',
        ),
        migrations.AddField(
            model_name='campana',
            name='archivo_excel',
            field=models.FileField(blank=True, help_text="Sube un archivo .xlsx con columnas: 'Nombre' y 'Telefono'. Se agregarán automáticamente.", null=True, upload_to='excels/'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='EnvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campana')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
        ),
    ]
