# Generated by Django 5.2.9 on 2025-12-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enviolog_respuesta_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Etiqueta de la línea, p.ej. FKWhatsapp', max_length=100)),
                ('numero', models.CharField(help_text='Número de la línea, p.ej. +573208198063', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='canal_envio',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voz', 'Voz')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='campana',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='linea_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.linea'),
        ),
    ]
