# Generated by Django 5.2.9 on 2025-12-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_whatsapplog_alter_campana_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tiene_imagen',
            field=models.BooleanField(default=False, help_text='¿Esta plantilla incluye una imagen?'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='url_imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen a enviar', max_length=500, null=True),
        ),
    ]
