# Generated by Django 5.2.9 on 2025-12-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plantilla_tiene_imagen_plantilla_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='proveedor',
            field=models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp')], default='meta', help_text='Proveedor de mensajería', max_length=20),
        ),
    ]
