# Generated by Django 5.2.9 on 2025-12-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campana_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='proveedor',
            field=models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp')], default='meta', help_text='Selecciona el proveedor de mensajería', max_length=20),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='twilio_template_sid',
            field=models.CharField(blank=True, help_text='Content Template SID de Twilio (ej: HXb4df6277ff3ad9a5b6c68993fed6ced8)', max_length=100, null=True),
        ),
    ]
