# Generated by Django 5.2.9 on 2025-12-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plantilla_proveedor_plantilla_twilio_template_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='tiene_imagen',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='twilio_template_sid',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='tipo',
            field=models.CharField(choices=[('INCOMING', 'Mensaje Recibido'), ('SENT', 'Mensaje Enviado')], default='INCOMING', max_length=20),
        ),
    ]
