# Generated by Django 5.2.9 on 2025-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_etiqueta_estudiante_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='#667eea', max_length=50, verbose_name='Color'),
        ),
    ]
