# Generated by Django 5.2.9 on 2025-12-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_campana_proveedor_remove_plantilla_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Café Arábigo', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa del curso')),
                ('emoji', models.CharField(default='📚', help_text='Emoji representativo', max_length=10)),
                ('duracion_semanas', models.IntegerField(default=5, help_text='Duración estimada en semanas')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones', models.TextField(default='Responde las siguientes preguntas sobre el curso:')),
                ('puntaje_minimo', models.IntegerField(default=70, help_text='Puntaje mínimo para aprobar (0-100)')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='core.curso')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del módulo (1-5)')),
                ('titulo', models.CharField(help_text='Ej: Siembra y Establecimiento', max_length=200)),
                ('descripcion', models.TextField(help_text='Breve descripción del módulo')),
                ('contenido', models.TextField(help_text='Contenido educativo completo del módulo')),
                ('duracion_dias', models.IntegerField(default=7, help_text='Días estimados para completar')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.estudiante')),
                ('modulo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulo')),
            ],
            options={
                'verbose_name': 'Progreso de Estudiante',
                'verbose_name_plural': 'Progresos de Estudiantes',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de la pregunta')),
                ('pregunta', models.TextField(help_text='Texto de la pregunta')),
                ('respuesta_correcta', models.TextField(help_text='Palabras clave o conceptos esperados en la respuesta (separados por comas)')),
                ('puntos', models.IntegerField(default=20, help_text='Puntos que vale esta pregunta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.examen')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Examen',
                'ordering': ['examen', 'numero'],
                'unique_together': {('examen', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ModuloCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modulo')),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_completados', to='core.progresoestudiante')),
            ],
            options={
                'verbose_name': 'Módulo Completado',
                'verbose_name_plural': 'Módulos Completados',
                'unique_together': {('progreso', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0, help_text='Puntaje obtenido (0-100)')),
                ('aprobado', models.BooleanField(default=False)),
                ('respuestas', models.JSONField(default=dict, help_text='Diccionario con las respuestas del estudiante')),
                ('feedback', models.TextField(blank=True, help_text='Retroalimentación generada por IA')),
                ('fecha_realizado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to='core.estudiante')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examen')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'unique_together': {('estudiante', 'examen')},
            },
        ),
    ]
