# Generated by Django 5.2.9 on 2025-12-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_curso_examen_modulo_progresoestudiante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': 'Plantillas de Mensajes'},
        ),
        migrations.AddField(
            model_name='plantilla',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si está desactivada, no aparecerá en las opciones de campaña', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='categoria',
            field=models.CharField(choices=[('educativo', '📚 Educativo'), ('motivacional', '💪 Motivacional'), ('informativo', 'ℹ️ Informativo'), ('promocional', '🎁 Promocional'), ('recordatorio', '⏰ Recordatorio'), ('bienvenida', '👋 Bienvenida'), ('otro', '📝 Otro')], default='informativo', help_text='Tipo de plantilla', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='veces_usada',
            field=models.IntegerField(default=0, help_text='Contador automático de veces que se ha usado', verbose_name='Veces usada'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='cuerpo_mensaje',
            field=models.TextField(help_text='Contenido del mensaje. Usa {nombre} para personalizar con el nombre del estudiante.', verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre_interno',
            field=models.CharField(help_text="Nombre interno para identificar la plantilla (ej: 'Bienvenida Estudiantes')", max_length=100, verbose_name='Nombre de la plantilla'),
        ),
    ]
