# Generated by Django 5.2.9 on 2025-12-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_etiqueta_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='filtro_etiquetas',
            field=models.ManyToManyField(blank=True, help_text='Si seleccionas etiquetas, solo se enviarán mensajes a estudiantes con AL MENOS UNA de estas etiquetas', related_name='campanas', to='core.etiqueta', verbose_name='Filtrar por etiquetas'),
        ),
    ]
