# Generated by Django 5.2.9 on 2025-12-23 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_campana_filtro_etiquetas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': 'Plantillas de Mensajes'},
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='tiene_imagen',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='url_imagen',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='activa',
            field=models.BooleanField(default=True, help_text='¿Esta plantilla está activa?', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipo_contenido',
            field=models.CharField(choices=[('texto', '📝 Solo Texto'), ('imagen', '🖼️ Con Imagen'), ('video', '🎥 Con Video'), ('archivo', '📎 Con Archivo')], default='texto', max_length=20, verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='twilio_variables',
            field=models.JSONField(blank=True, help_text='Variables del template en formato JSON: {"1": "nombre", "2": "materia"}', null=True, verbose_name='Variables del template'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='url_media',
            field=models.URLField(blank=True, help_text='URL del archivo multimedia (imagen, video, documento)', max_length=500, null=True, verbose_name='URL de media'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='cuerpo_mensaje',
            field=models.TextField(help_text='Usa {{nombre}} para personalizar', verbose_name='Contenido del mensaje'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre_interno',
            field=models.CharField(max_length=100, verbose_name='Nombre interno'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='proveedor',
            field=models.CharField(choices=[('meta', 'Meta WhatsApp Cloud API'), ('twilio', 'Twilio WhatsApp')], default='twilio', help_text='Selecciona el proveedor de mensajería', max_length=20, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='twilio_template_sid',
            field=models.CharField(blank=True, help_text='Content Template SID de Twilio (ej: HXb4df6277ff3ad9a5b6c68993fed6ced8)', max_length=100, null=True, verbose_name='Content SID (Twilio)'),
        ),
    ]
