# Generated by Django 5.2.9 on 2025-12-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_plantilla_options_plantilla_activa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de WhatsApp', 'verbose_name_plural': 'Registros de WhatsApp'},
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='estudiante',
            field=models.ForeignKey(blank=True, help_text='Estudiante asociado a esta conversación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='core.estudiante'),
        ),
        migrations.AddIndex(
            model_name='whatsapplog',
            index=models.Index(fields=['-fecha'], name='core_whatsa_fecha_47f0df_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapplog',
            index=models.Index(fields=['telefono', '-fecha'], name='core_whatsa_telefon_6fa1b1_idx'),
        ),
    ]
