# Generated by Django 5.2.9 on 2025-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_plantilla_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Mensaje WhatsApp', 'verbose_name_plural': '💬 Mensajes WhatsApp (REAL)'},
        ),
        migrations.RemoveField(
            model_name='whatsapplog',
            name='estado',
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='tipo',
            field=models.CharField(choices=[('SENT', 'Enviado'), ('INCOMING', 'Recibido')], default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['telefono', 'activo'], name='core_estudi_telefon_0631bb_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['activo', '-fecha_registro'], name='core_estudi_activo_80ac18_idx'),
        ),
    ]
