# Generated by Django 5.2.9 on 2025-12-31 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agregar_estudiante_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Café, Aguacate, Maíz, Motivación General', max_length=50, unique=True, verbose_name='Nombre del tema')),
                ('emoji', models.CharField(blank=True, help_text='Emoji representativo (ej: ☕, 🥑, 🌽)', max_length=10, verbose_name='Emoji')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del tema', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en las opciones', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tema de Campaña',
                'verbose_name_plural': 'Temas de Campañas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='campana',
            name='tema',
            field=models.ForeignKey(blank=True, help_text='Selecciona el tema (ej: Café, Aguacate). Solo se mostrarán plantillas de este tema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='core.temacampana', verbose_name='Tema principal'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='temas',
            field=models.ManyToManyField(blank=True, help_text='Selecciona uno o más temas relacionados (ej: Café, Motivación)', related_name='plantillas', to='core.temacampana', verbose_name='Temas'),
        ),
    ]
