# Generated by Django 5.2.9 on 2025-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_temacampana_campana_tema_plantilla_temas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='canal_envio',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', help_text='Actualmente solo se soporta WhatsApp', max_length=20, verbose_name='Canal de Envío'),
        ),
    ]
