# Generated by Django 5.2.9 on 2025-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_campana_canal_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='enviada_a_meta',
            field=models.BooleanField(default=False, help_text='Indica si la plantilla fue enviada a Meta para aprobación', verbose_name='Enviada a Meta'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='meta_template_id',
            field=models.CharField(blank=True, help_text='ID asignado por Meta al enviar la plantilla para revisión', max_length=100, null=True, verbose_name='ID de Plantilla en Meta'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='meta_template_name',
            field=models.CharField(blank=True, help_text='Nombre sanitizado usado en Meta (minúsculas, guiones bajos)', max_length=100, null=True, verbose_name='Nombre en Meta'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='meta_template_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('DISABLED', 'Deshabilitada')], help_text='Estado de aprobación de la plantilla en Meta', max_length=50, null=True, verbose_name='Estado en Meta'),
        ),
    ]
