# Generated by Django 5.2.9 on 2025-12-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plantilla_enviada_a_meta_plantilla_meta_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='agente_usado',
            field=models.CharField(blank=True, help_text='Nombre del agente IA que generó la respuesta', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='audio_path',
            field=models.CharField(blank=True, help_text='Ruta local del archivo de audio descargado', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='audio_transcripcion',
            field=models.TextField(blank=True, help_text='Transcripción del audio (generada por Whisper)', null=True),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL del archivo de audio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='es_audio',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje es un audio'),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='tema_detectado',
            field=models.CharField(blank=True, help_text='Tema detectado en la conversación (café, aguacate, etc.)', max_length=100, null=True),
        ),
    ]
