# Generated by Django 5.2.9 on 2025-12-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_whatsapplog_agente_usado_whatsapplog_audio_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='🏆', help_text='Emoji del badge', max_length=10)),
                ('tipo', models.CharField(choices=[('NIVEL', 'Por alcanzar nivel'), ('RACHA', 'Por mantener racha'), ('CURSO', 'Por completar curso'), ('EXAMEN', 'Por aprobar examen'), ('PARTICIPACION', 'Por participación activa'), ('ESPECIAL', 'Badge especial')], max_length=20)),
                ('nivel_requerido', models.IntegerField(blank=True, help_text='Nivel necesario (solo para tipo NIVEL)', null=True)),
                ('valor_requerido', models.IntegerField(blank=True, help_text='Valor requerido (días de racha, cursos completados, etc.)', null=True)),
                ('puntos_bonus', models.IntegerField(default=0, help_text='Puntos extra al obtener este badge')),
                ('es_secreto', models.BooleanField(default=False, help_text='Si es secreto, no se muestra hasta obtenerlo')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso_requerido', models.ForeignKey(blank=True, help_text='Curso específico requerido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilGamificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0, help_text='Puntos acumulados totales')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel actual del estudiante')),
                ('experiencia_nivel_actual', models.IntegerField(default=0, help_text='Experiencia en el nivel actual')),
                ('racha_dias_actual', models.IntegerField(default=0, help_text='Días consecutivos de actividad actual')),
                ('racha_dias_maxima', models.IntegerField(default=0, help_text='Récord de días consecutivos')),
                ('ultima_actividad', models.DateTimeField(blank=True, help_text='Última vez que tuvo actividad', null=True)),
                ('modulos_completados', models.IntegerField(default=0)),
                ('examenes_aprobados', models.IntegerField(default=0)),
                ('preguntas_respondidas', models.IntegerField(default=0)),
                ('audios_enviados', models.IntegerField(default=0)),
                ('posicion_ranking', models.IntegerField(default=0, help_text='Posición en el ranking global')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacion', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Perfil de Gamificación',
                'verbose_name_plural': 'Perfiles de Gamificación',
                'ordering': ['-puntos_totales'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('tipo', models.CharField(choices=[('GANANCIA', 'Ganó puntos'), ('GASTO', 'Gastó puntos'), ('BONUS', 'Bonus especial')], max_length=20)),
                ('razon', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.perfilgamificacion')),
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'verbose_name_plural': 'Transacciones de Puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BadgeEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.badge')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_obtenidos', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Badge de Estudiante',
                'verbose_name_plural': 'Badges de Estudiantes',
                'ordering': ['-fecha_obtenido'],
                'unique_together': {('estudiante', 'badge')},
            },
        ),
    ]
