# Generated by Django 5.2.9 on 2026-01-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_badge_perfilgamificacion_transaccionpuntos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='archivo_pdf_url',
            field=models.URLField(blank=True, help_text='Material PDF descargable', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='imagen_portada_url',
            field=models.URLField(blank=True, help_text='Imagen de portada del módulo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='Archivo de video (MP4, baja resolución recomendada para el campo)', null=True, upload_to='videos/lecciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video_resolucion',
            field=models.CharField(choices=[('360p', '360p - Baja (recomendado campo)'), ('480p', '480p - Media'), ('720p', '720p - Alta')], default='360p', help_text='Resolución del video (baja = menos datos)', max_length=20),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video (YouTube, Vimeo, archivo directo)', max_length=500, null=True),
        ),
    ]
