# Generated by Django 5.2.9 on 2026-01-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_modulo_archivo_pdf_url_modulo_imagen_portada_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cooperativa Cafetera del Valle, Fundación Agrícola', max_length=200, verbose_name='Nombre del Cliente')),
                ('nit', models.CharField(blank=True, help_text='Número de identificación tributaria', max_length=20, verbose_name='NIT/RUT')),
                ('contacto_principal', models.CharField(help_text='Nombre de la persona de contacto', max_length=100, verbose_name='Contacto Principal')),
                ('email', models.EmailField(help_text='Email de contacto del cliente', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, sus estudiantes no recibirán mensajes', verbose_name='Activo')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas para uso interno de Eki (no visibles para el cliente)', verbose_name='Notas Internas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='campana',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente para el que es esta campaña', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Si es para un cliente específico. Dejar vacío = curso general de Eki disponible para todos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.cliente', verbose_name='Cliente Específico'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente/Organización a la que pertenece este estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
