# Generated by Django 5.2.9 on 2026-01-08 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cliente_campana_cliente_curso_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la recompensa', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la recompensa')),
                ('icono', models.CharField(default='🎁', help_text='Emoji para mostrar', max_length=10)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen promocional', null=True)),
                ('tipo', models.CharField(choices=[('DIGITAL', 'Digital (PDF, Video, Guía)'), ('DESCUENTO', 'Descuento en Productos'), ('CERTIFICADO', 'Certificado Especial'), ('CONSULTORIA', 'Consultoría 1-a-1'), ('ACCESO', 'Acceso a Contenido Premium'), ('FISICO', 'Producto Físico (Semillas, Herramientas)'), ('EVENTO', 'Entrada a Evento'), ('OTRO', 'Otro')], default='DIGITAL', max_length=20)),
                ('puntos_requeridos', models.IntegerField(help_text='Puntos que cuesta canjear esta recompensa', validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('PROXIMO', 'Próximamente'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('cantidad_disponible', models.IntegerField(blank=True, help_text='Dejar vacío para cantidad ilimitada', null=True)),
                ('cantidad_canjeada', models.IntegerField(default=0, editable=False)),
                ('nivel_minimo', models.IntegerField(blank=True, help_text='Nivel mínimo del estudiante para canjear (opcional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha desde cuando está disponible (opcional)', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha hasta cuando está disponible (opcional)', null=True)),
                ('instrucciones_entrega', models.TextField(blank=True, help_text='Instrucciones para entregar la recompensa al estudiante')),
                ('enlace_descarga', models.URLField(blank=True, help_text='Link directo para recompensas digitales')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en catálogo')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar como destacado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['-destacado', 'orden', 'puntos_requeridos'],
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_gastados', models.IntegerField(help_text='Puntos gastados en este canje')),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Entrega'), ('PROCESANDO', 'Procesando'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('nota_entrega', models.TextField(blank=True, help_text='Notas sobre la entrega (tracking, confirmación, etc.)')),
                ('atendido_por', models.CharField(blank=True, help_text='Miembro del equipo EKI que procesó el canje', max_length=100)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_canjeadas', to='core.estudiante')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.recompensa')),
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Canjes de Recompensas',
                'ordering': ['-fecha_canje'],
            },
        ),
    ]
