# Generated by Django 5.2.9 on 2026-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_recompensa_canjerecompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='aprobada_twilio',
            field=models.BooleanField(default=False, help_text='Marca esto cuando tu plantilla esté aprobada en Twilio Console', verbose_name='Aprobada en Twilio'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='twilio_template_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la plantilla en Twilio Console (para referencia)', max_length=100, null=True, verbose_name='Nombre en Twilio'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='twilio_template_sid',
            field=models.CharField(blank=True, help_text='Content SID de Twilio (ej: HX1234...). Obtén esto desde Twilio Console después de crear tu plantilla aprobada.', max_length=50, null=True, verbose_name='Twilio Content SID'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='enviada_a_meta',
            field=models.BooleanField(default=False, help_text='No usar - Solo Twilio', verbose_name='[Deprecated] Enviada a Meta'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='meta_template_id',
            field=models.CharField(blank=True, help_text='No usar - Solo Twilio', max_length=100, null=True, verbose_name='[Deprecated] ID de Plantilla en Meta'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='meta_template_name',
            field=models.CharField(blank=True, help_text='No usar - Solo Twilio', max_length=100, null=True, verbose_name='[Deprecated] Nombre en Meta'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='meta_template_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('DISABLED', 'Deshabilitada')], help_text='No usar - Solo Twilio', max_length=50, null=True, verbose_name='[Deprecated] Estado en Meta'),
        ),
    ]
