# Generated by Django 5.2.9 on 2026-01-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_populate_cedula_make_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_original', models.TextField(help_text='El mensaje que envió el estudiante pidiendo ayuda', verbose_name='Mensaje del Estudiante')),
                ('keyword_usada', models.CharField(blank=True, help_text='Keyword que activó el soporte (AYUDA, SOPORTE, HUMANO, etc.)', max_length=20, verbose_name='Palabra Clave')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('en_atencion', '👀 En Atención'), ('resuelta', '✅ Resuelta'), ('cerrada', '🔒 Cerrada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', '🟢 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta'), ('critica', '🚨 Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta que se le dio al estudiante', verbose_name='Respuesta del Equipo')),
                ('atendido_por', models.CharField(blank=True, help_text='Nombre del miembro del equipo que atendió', max_length=100, verbose_name='Atendido Por')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Atención')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas privadas del equipo (no visible para el estudiante)', verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Solicitud de Soporte',
                'verbose_name_plural': '🆘 Solicitudes de Soporte',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AlterModelOptions(
            name='campana',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': '📢 Campañas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': '👥 Clientes (Organizaciones)'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': '👥 Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': '📚 Cursos → Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': '📢 Campañas → Plantillas'},
        ),
        migrations.AlterModelOptions(
            name='progresoestudiante',
            options={'verbose_name': 'Progreso de Estudiante', 'verbose_name_plural': '📚 Cursos → Progreso'},
        ),
        migrations.AlterModelOptions(
            name='temacampana',
            options={'ordering': ['nombre'], 'verbose_name': 'Tema de Campaña', 'verbose_name_plural': '📢 Campañas → Temas'},
        ),
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de WhatsApp', 'verbose_name_plural': '📢 Campañas → Historial WhatsApp'},
        ),
        migrations.RenameIndex(
            model_name='estudiante',
            new_name='core_estudi_cedula_efd1fe_idx',
            old_name='core_estudia_cedula_idx',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='acepto_terminos',
            field=models.BooleanField(default=False, help_text='Indica si el estudiante aceptó la política de tratamiento de datos', verbose_name='Aceptó Términos y Condiciones'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que aceptó los términos', null=True, verbose_name='Fecha de Aceptación'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['telefono'], name='core_estudi_telefon_47e0ee_idx'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to='core.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['estado', 'prioridad'], name='core_solici_estado_223cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['estudiante', 'fecha_solicitud'], name='core_solici_estudia_5b143e_idx'),
        ),
    ]
