# Generated by Django 5.2.9 on 2026-01-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_solicitudsoporte_alter_campana_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temacampana',
            name='emoji',
            field=models.CharField(blank=True, help_text='Copia y pega uno: ☕ 🥑 🌽 🍌 🍊 🍇 🥔 🥕 🧅 🌶️ 🫘 🥬 🍅 🥒 🥦 🐄 🐔 🐷 🐑 🌱 🌾 🌳 🚜 💧 🌤️', max_length=10, verbose_name='Emoji'),
        ),
    ]
