# Generated by Django 5.2.9 on 2026-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_temacampana_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado_onboarding',
            field=models.CharField(default='nuevo', help_text='nuevo, esperando_cedula, completado', max_length=20, verbose_name='Estado Onboarding'),
        ),
    ]
