# Generated by Django 5.2.9 on 2026-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_estudiante_estado_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', help_text='Tipo de documento de identificación', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(help_text='Número de identificación único', max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_onboarding',
            field=models.CharField(default='nuevo', help_text='nuevo, esperando_tipo_doc, esperando_cedula, completado', max_length=30, verbose_name='Estado Onboarding'),
        ),
    ]
