# Generated by Django 5.2.9 on 2026-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_estudiante_tipo_documento_alter_estudiante_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_onboarding',
            field=models.CharField(default='nuevo', help_text='nuevo, esperando_tipo_doc, esperando_cedula, esperando_nombre, completado', max_length=30, verbose_name='Estado Onboarding'),
        ),
    ]
