# Generated by Django 5.2.9 on 2026-01-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_agregar_estado_esperando_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulocompletado',
            name='respuesta_correcta',
            field=models.BooleanField(default=False, help_text='Si respondió correctamente'),
        ),
        migrations.AddField(
            model_name='modulocompletado',
            name='respuesta_dada',
            field=models.CharField(blank=True, help_text='A, B, C o D', max_length=1),
        ),
        migrations.CreateModel(
            name='PreguntaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(help_text='Pregunta de validación del aprendizaje')),
                ('opcion_a', models.CharField(max_length=500)),
                ('opcion_b', models.CharField(max_length=500)),
                ('opcion_c', models.CharField(blank=True, max_length=500, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=500, null=True)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Letra de la respuesta correcta', max_length=1)),
                ('explicacion', models.TextField(blank=True, help_text='Explicación de la respuesta correcta (opcional)')),
                ('activa', models.BooleanField(default=True, help_text='Si está desactivada, no se mostrará')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Pregunta de Módulo',
                'verbose_name_plural': '📝 Cursos → Preguntas por Módulo',
                'ordering': ['modulo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='modulocompletado',
            name='pregunta_respondida',
            field=models.ForeignKey(blank=True, help_text='Pregunta que se le hizo al completar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.preguntamodulo'),
        ),
    ]
