# Generated by Django 5.2.9 on 2026-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_modulocompletado_respuesta_correcta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contexto_temporal',
            field=models.JSONField(blank=True, help_text='Guarda el módulo_id y pregunta_id actual cuando está respondiendo mini examen', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_onboarding',
            field=models.CharField(default='nuevo', help_text='nuevo, esperando_tipo_doc, esperando_cedula, esperando_nombre, esperando_respuesta_modulo, completado', max_length=50, verbose_name='Estado Onboarding'),
        ),
    ]
