# Generated by Django 5.2.9 on 2026-01-11 05:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_estudiante_contexto_temporal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_fondo', models.ImageField(blank=True, help_text='Imagen de fondo del certificado', null=True, upload_to='certificados/plantillas/')),
                ('logo_institucion', models.ImageField(blank=True, help_text='Logo de EKI', null=True, upload_to='certificados/logos/')),
                ('color_primario', models.CharField(default='#2C3E50', help_text='Color principal (ej: #2C3E50)', max_length=7)),
                ('color_secundario', models.CharField(default='#3498DB', help_text='Color secundario', max_length=7)),
                ('texto_superior', models.CharField(default='EKI - Educación Agrícola', help_text='Texto en la parte superior', max_length=200)),
                ('texto_certificado', models.CharField(default='CERTIFICADO DE FINALIZACIÓN', help_text='Título del certificado', max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('por_defecto', models.BooleanField(default=False, help_text='Plantilla por defecto para nuevos certificados')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Certificado',
                'verbose_name_plural': 'Plantillas de Certificados',
                'ordering': ['-por_defecto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.CharField(editable=False, help_text='Código único de verificación', max_length=50, unique=True)),
                ('calificacion_final', models.DecimalField(decimal_places=2, help_text='Calificación final (0-100)', max_digits=5)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del curso')),
                ('fecha_completado', models.DateField(default=django.utils.timezone.now, help_text='Fecha de finalización del curso')),
                ('emitido', models.BooleanField(default=False, help_text='Si el certificado fue generado y enviado')),
                ('fecha_emision', models.DateTimeField(blank=True, help_text='Fecha de emisión del certificado', null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Certificado en PDF', null=True, upload_to='certificados/%Y/%m/')),
                ('enviado_whatsapp', models.BooleanField(default=False, help_text='Si fue enviado por WhatsApp')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_emitidos', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision', '-creado_en'],
                'indexes': [models.Index(fields=['codigo_verificacion'], name='core_certif_codigo__64b912_idx'), models.Index(fields=['estudiante', 'curso'], name='core_certif_estudia_70b7dd_idx')],
            },
        ),
    ]
