# Generated by Django 5.2.9 on 2026-01-11 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_plantillacertificado_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('GENERAR', 'Generar certificado'), ('ENVIAR', 'Enviar por WhatsApp'), ('DESCARGAR', 'Descargar PDF'), ('VERIFICAR', 'Verificar (público)'), ('MODIFICAR', 'Modificar detalles'), ('ELIMINAR', 'Eliminar'), ('REGENERAR', 'Regenerar PDF'), ('AUTO_GENERAR', 'Auto-generar (signal)'), ('ERROR', 'Error en proceso')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales de la acción', verbose_name='Descripción')),
                ('certificado_codigo', models.CharField(blank=True, max_length=50, verbose_name='Código de Certificado')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Estudiante')),
                ('curso_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Curso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('exitoso', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (vacío si fue automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': '🔐 Sistema → Auditoría',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['-fecha_accion'], name='core_auditl_fecha_a_977a0f_idx'), models.Index(fields=['accion'], name='core_auditl_accion_ee46dd_idx'), models.Index(fields=['certificado_codigo'], name='core_auditl_certifi_9f8a2c_idx')],
            },
        ),
    ]
