# Generated by Django 5.2.9 on 2026-01-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_emision', '-creado_en'], 'verbose_name': '📜 Certificado', 'verbose_name_plural': '📜 Certificados'},
        ),
        migrations.AlterModelOptions(
            name='plantillacertificado',
            options={'ordering': ['-por_defecto', 'nombre'], 'verbose_name': '🎨 Plantilla de Certificado', 'verbose_name_plural': '🎨 Plantillas de Certificados'},
        ),
    ]
