# Generated by Django 5.2.9 on 2026-01-13 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_certificado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usar_gamificacion',
            field=models.BooleanField(default=True, help_text='Si está activado, se otorgan puntos y badges en este curso', verbose_name='Usar Gamificación'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='examen_obligatorio',
            field=models.BooleanField(default=False, help_text='El estudiante DEBE aprobar el examen para avanzar al siguiente módulo', verbose_name='Examen Obligatorio'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='puntaje_minimo_aprobacion',
            field=models.IntegerField(default=70, help_text='Porcentaje mínimo para aprobar (0-100)', verbose_name='Puntaje Mínimo (%)'),
        ),
        migrations.CreateModel(
            name='ArchivoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('imagen', 'Imagen'), ('infografia', 'Infografía'), ('pdf', 'Documento PDF'), ('audio', 'Audio')], max_length=20, verbose_name='Tipo de Archivo')),
                ('titulo', models.CharField(help_text='Ej: Video explicativo sobre riego', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(help_text='Archivo multimedia', upload_to='modulos/%Y/%m/', verbose_name='Archivo')),
                ('url_externa', models.URLField(blank=True, help_text='URL alternativa (YouTube, etc.)', max_length=500, null=True, verbose_name='URL Externa')),
                ('disponible_offline', models.BooleanField(default=True, help_text='Si está activado, se puede descargar para ver offline', verbose_name='Disponible sin Conexión')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización dentro del módulo', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Solo para videos/audios', null=True, verbose_name='Duración (segundos)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_multimedia', to='core.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': '📁 Archivos Multimedia',
                'ordering': ['modulo', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cafeteros Zona Norte, Aguacateros 2026', max_length=100, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del grupo y su propósito', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_estudiantes', to='core.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='grupos', to='core.estudiante', verbose_name='Estudiantes')),
            ],
            options={
                'verbose_name': 'Grupo de Estudiantes',
                'verbose_name_plural': '👥 Grupos de Estudiantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GrupoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Curso de Café - Grupo 1', max_length=100, verbose_name='Nombre del Grupo')),
                ('descripcion', models.TextField(help_text='Descripción del grupo y su propósito', verbose_name='Descripción')),
                ('link_invitacion', models.URLField(help_text='Link de invitación del grupo de WhatsApp (https://chat.whatsapp.com/...)', max_length=500, verbose_name='Link de Invitación')),
                ('capacidad_maxima', models.IntegerField(default=256, help_text='Capacidad máxima del grupo (límite de WhatsApp: 1024)', verbose_name='Capacidad Máxima')),
                ('miembros_actuales', models.IntegerField(default=0, verbose_name='Miembros Actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_whatsapp', to='core.curso', verbose_name='Curso Relacionado')),
            ],
            options={
                'verbose_name': 'Grupo de WhatsApp',
                'verbose_name_plural': '💬 Grupos de WhatsApp',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EnvioProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar este envío', max_length=200, verbose_name='Nombre del Envío')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo Completo'), ('campana', 'Campaña Masiva')], default='grupo', max_length=20, verbose_name='Tipo de Envío')),
                ('mensaje', models.TextField(help_text='Mensaje a enviar', verbose_name='Mensaje')),
                ('incluir_media', models.BooleanField(default=False, verbose_name='Incluir Multimedia')),
                ('media_url', models.URLField(blank=True, help_text='URL de imagen, video o PDF a adjuntar', max_length=500, null=True, verbose_name='URL del Archivo')),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora en la que se debe enviar', verbose_name='Fecha y Hora Programada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_envio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío Real')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total Destinatarios')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Total Enviados')),
                ('total_fallidos', models.IntegerField(default=0, verbose_name='Total Fallidos')),
                ('error', models.TextField(blank=True, verbose_name='Errores')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_programados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('estudiante', models.ForeignKey(blank=True, help_text='Estudiante individual (solo si tipo=individual)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_programados', to='core.estudiante', verbose_name='Estudiante')),
                ('grupo', models.ForeignKey(blank=True, help_text='Grupo de estudiantes a quien enviar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_programados', to='core.grupoestudiantes', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Envío Programado',
                'verbose_name_plural': '📅 Envíos Programados',
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='core_enviop_estado_e9e996_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvitacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_grupo', to='core.estudiante', verbose_name='Estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.grupowhatsapp', verbose_name='Grupo de WhatsApp')),
            ],
            options={
                'verbose_name': 'Invitación a Grupo',
                'verbose_name_plural': '✉️ Invitaciones a Grupos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('grupo', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('felicitacion', 'Felicitación')], max_length=20, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas para uso interno del equipo', verbose_name='Notas Internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('calificacion', models.IntegerField(blank=True, help_text='Del 1 al 5, otorgada por el estudiante', null=True, verbose_name='Calificación')),
                ('comentario_calificacion', models.TextField(blank=True, verbose_name='Comentario de Calificación')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('curso_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso Relacionado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='core.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': '📮 PQRS (Peticiones/Quejas/Reclamos/Sugerencias)',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'fecha_creacion'], name='core_pqrs_estado_b199bf_idx'), models.Index(fields=['estudiante', 'estado'], name='core_pqrs_estudia_f225e0_idx')],
            },
        ),
    ]
