# Generated by Django 5.2.9 on 2026-01-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_curso_usar_gamificacion_modulo_examen_obligatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Selecciona el grupo al que se enviará la campaña', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='core.grupoestudiantes', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='campana',
            name='tipo_audiencia',
            field=models.CharField(choices=[('individual', 'Estudiantes individuales'), ('grupo', 'Grupo de estudiantes')], default='individual', help_text='Selecciona si quieres enviar a estudiantes individuales o a un grupo', max_length=20, verbose_name='Tipo de audiencia'),
        ),
        migrations.AddField(
            model_name='grupoestudiantes',
            name='cursos',
            field=models.ManyToManyField(blank=True, help_text='Cursos relacionados con este grupo (opcional)', related_name='grupos', to='core.curso', verbose_name='Cursos Asociados'),
        ),
        migrations.AddField(
            model_name='grupoestudiantes',
            name='emoji',
            field=models.CharField(default='👥', help_text='Emoji representativo del grupo', max_length=10, verbose_name='Emoji'),
        ),
    ]
