# Generated by Django 5.2.9 on 2026-01-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_campana_grupo_campana_tipo_audiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudiantes',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente al que pertenece el grupo (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_estudiantes', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
