# Generated by Django 5.2.9 on 2026-01-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_grupoestudiantes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enviar_certificados_email',
            field=models.BooleanField(default=True, help_text='Si está activado, se enviarán los certificados de sus estudiantes al email del cliente', verbose_name='Enviar Certificados por Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_whatsapp_autorizado',
            field=models.CharField(blank=True, help_text='Número autorizado en Meta Business para envío masivo (ej: 573001234567)', max_length=20, verbose_name='Número WhatsApp Autorizado en Meta'),
        ),
    ]
