# Generated by Django 5.2.9 on 2026-01-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_cliente_enviar_certificados_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enlace_grupo_whatsapp',
            field=models.URLField(blank=True, help_text='Enlace de invitación al grupo de WhatsApp del cliente (ej: https://chat.whatsapp.com/xxxxx)', max_length=500, verbose_name='Enlace de Grupo de WhatsApp'),
        ),
        migrations.AddField(
            model_name='curso',
            name='enlace_grupo_whatsapp',
            field=models.URLField(blank=True, help_text='Enlace de invitación al grupo de WhatsApp del curso (ej: https://chat.whatsapp.com/xxxxx)', max_length=500, verbose_name='Enlace de Grupo de WhatsApp'),
        ),
    ]
