# Generated by Django 5.2.9 on 2026-01-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_cliente_enlace_grupo_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='archivo_plantilla_pdf',
            field=models.FileField(blank=True, help_text='📤 Sube tu propia plantilla en PDF. Solo necesita tener espacio para el NOMBRE del estudiante.', null=True, upload_to='certificados/plantillas_personalizadas/'),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Si es para un cliente específico. Dejar vacío = plantilla general de Eki', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_certificados', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='variable_curso',
            field=models.CharField(default='{curso}', help_text='Variable a reemplazar por el nombre del curso', max_length=50),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='variable_fecha',
            field=models.CharField(default='{fecha}', help_text='Variable a reemplazar por la fecha', max_length=50),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='variable_nombre',
            field=models.CharField(default='{nombre}', help_text='Variable a reemplazar por el nombre del estudiante (ej: {nombre}, [NOMBRE], {{nombre}})', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción opcional de cuándo usar esta plantilla'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo del certificado (si no subes PDF)', null=True, upload_to='certificados/plantillas/'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='logo_institucion',
            field=models.ImageField(blank=True, help_text='Logo de la institución', null=True, upload_to='certificados/logos/'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='nombre',
            field=models.CharField(help_text="Nombre identificador de la plantilla (ej: 'Plantilla Cargill', 'Plantilla TechnoServe')", max_length=100),
        ),
    ]
