# Generated by Django 5.2.9 on 2026-01-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_plantillacertificado_archivo_plantilla_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='temas',
        ),
        migrations.AddField(
            model_name='campana',
            name='categoria',
            field=models.CharField(choices=[('cultivos', '🌾 Cultivos'), ('ganaderia', '🐄 Ganadería'), ('general_agricola', '🌱 General Agrícola'), ('educacion', '📚 Educación'), ('gestion', '💼 Gestión'), ('todas', '📋 Todas las categorías')], default='todas', help_text="Filtrar plantillas por categoría. 'Todas' mostrará plantillas de cualquier categoría.", max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='envioprogramado',
            name='campana',
            field=models.ForeignKey(blank=True, help_text='Campaña a la que pertenece este envío programado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_programados', to='core.campana', verbose_name='Campaña'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='emoji',
            field=models.CharField(blank=True, help_text='Emoji que representa esta plantilla (se autocompletará según la categoría)', max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='categoria',
            field=models.CharField(choices=[('cultivos', '🌾 Cultivos'), ('ganaderia', '🐄 Ganadería'), ('general_agricola', '🌱 General Agrícola'), ('educacion', '📚 Educación'), ('gestion', '💼 Gestión'), ('otro', '📝 Otro')], default='cultivos', help_text='Categoría principal de la plantilla', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre_interno',
            field=models.CharField(help_text="Nombre interno para identificar la plantilla (ej: 'Recordatorio Riego Café')", max_length=100, verbose_name='Nombre de la plantilla'),
        ),
    ]
