# Generated by Django 5.2.9 on 2026-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_simplify_plantillas_remove_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usar_gamificacion',
            field=models.BooleanField(default=True, help_text='Si está activado, los estudiantes de este cliente podrán ver puntos, badges y recompensas. Si está desactivado, solo verán el contenido educativo.', verbose_name='🎮 Usar Gamificación'),
        ),
    ]
