# Generated by Django 5.2.9 on 2026-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cliente_usar_gamificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campana',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes (Organizaciones)'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': 'Plantillas de Mensaje'},
        ),
        migrations.AlterModelOptions(
            name='preguntamodulo',
            options={'ordering': ['modulo', 'id'], 'verbose_name': 'Pregunta de Módulo', 'verbose_name_plural': 'Preguntas de Módulos'},
        ),
        migrations.AlterModelOptions(
            name='progresoestudiante',
            options={'verbose_name': 'Progreso de Estudiante', 'verbose_name_plural': 'Progreso de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='temacampana',
            options={'ordering': ['nombre'], 'verbose_name': 'Tema de Campaña', 'verbose_name_plural': 'Temas de Campaña'},
        ),
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de WhatsApp', 'verbose_name_plural': 'Historial WhatsApp'},
        ),
        migrations.AlterField(
            model_name='archivomodulo',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube imagen, video, PDF o audio desde tu computadora (se guarda en AWS S3)', null=True, upload_to='modulos/%Y/%m/', verbose_name='Subir Archivo desde PC'),
        ),
        migrations.AlterField(
            model_name='archivomodulo',
            name='url_externa',
            field=models.URLField(blank=True, help_text='Alternativa: Pega enlace de YouTube, Google Drive, Imgur, etc. (solo si NO subes archivo)', max_length=500, null=True, verbose_name='O usar URL Externa'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='categoria',
            field=models.CharField(choices=[('cultivos', 'Cultivos'), ('ganaderia', 'Ganadería'), ('general_agricola', 'General Agrícola'), ('educacion', 'Educación'), ('gestion', 'Gestión'), ('todas', 'Todas las categorías')], default='todas', help_text="Filtrar plantillas por categoría. 'Todas' mostrará plantillas de cualquier categoría.", max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usar_gamificacion',
            field=models.BooleanField(default=True, help_text='Si está activado, los estudiantes de este cliente podrán ver puntos, badges y recompensas. Si está desactivado, solo verán el contenido educativo.', verbose_name='Usar Gamificación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='emoji',
            field=models.CharField(blank=True, default='', help_text='Emoji representativo (opcional)', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='categoria',
            field=models.CharField(choices=[('cultivos', 'Cultivos'), ('ganaderia', 'Ganadería'), ('general_agricola', 'General Agrícola'), ('educacion', 'Educación'), ('gestion', 'Gestión'), ('otro', 'Otro')], default='cultivos', help_text='Categoría principal de la plantilla', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_atencion', 'En Atención'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
