# Generated by Django 5.2.9 on 2026-02-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_hacer_archivo_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='numero',
            field=models.DecimalField(decimal_places=2, help_text='Número del módulo (acepta decimales: 1, 1.1, 1.2, 2, etc.)', max_digits=5),
        ),
    ]
