# Generated by Django 5.2.9 on 2026-02-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_cambiar_numero_modulo_a_decimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivomodulo',
            options={'ordering': ['modulo', 'orden', 'id'], 'verbose_name': 'Archivo Multimedia', 'verbose_name_plural': 'Archivos Multimedia'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento/Estado donde reside', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio donde reside el estudiante', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ubicacion_detalle',
            field=models.TextField(blank=True, help_text='Vereda, barrio o información adicional de ubicación', verbose_name='Ubicación Detalle'),
        ),
        migrations.CreateModel(
            name='ObjetivoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('especifico', 'Específico')], default='especifico', max_length=20, verbose_name='Tipo de Objetivo')),
                ('orden', models.IntegerField(default=0, help_text='Orden del objetivo')),
                ('descripcion', models.TextField(help_text='Descripción del objetivo de aprendizaje')),
                ('peso_evaluacion', models.IntegerField(default=25, help_text='Peso porcentual de este objetivo en la evaluación (0-100)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='core.curso')),
            ],
            options={
                'verbose_name': 'Objetivo de Curso',
                'verbose_name_plural': 'Objetivos de Cursos',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RubricaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la rúbrica', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción de qué evalúa')),
                ('criterios', models.JSONField(default=dict, help_text='Criterios de evaluación en formato JSON: {"criterio1": {"excelente": 100, "bueno": 75, "regular": 50, "insuficiente": 25}}')),
                ('palabras_clave', models.TextField(blank=True, help_text='Palabras clave esperadas en respuestas correctas (separadas por comas)')),
                ('activa', models.BooleanField(default=True)),
                ('objetivo', models.ForeignKey(blank=True, help_text='Objetivo al que pertenece esta rúbrica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='core.objetivocurso')),
            ],
            options={
                'verbose_name': 'Rúbrica de Evaluación',
                'verbose_name_plural': 'Rúbricas de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='EjercicioPractico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('numerico', 'Numérico (cálculos)'), ('abierto', 'Respuesta Abierta'), ('hipotetico', 'Situación Hipotética'), ('comprension', '¿Entendiste? (comprensión)')], default='comprension', max_length=20)),
                ('enunciado', models.TextField(help_text='Texto del ejercicio o situación hipotética')),
                ('contexto_previo', models.TextField(blank=True, help_text='Contexto o información necesaria para resolver el ejercicio')),
                ('respuesta_numerica_esperada', models.DecimalField(blank=True, decimal_places=2, help_text='Respuesta numérica correcta (ej: utilidad esperada)', max_digits=15, null=True)),
                ('tolerancia_porcentual', models.IntegerField(default=5, help_text='Tolerancia de error aceptable en porcentaje (ej: 5 = ±5%)')),
                ('formula_evaluacion', models.TextField(blank=True, help_text='Fórmula o criterio para evaluar (ej: "ingresos - costos = utilidad")')),
                ('puntaje_maximo', models.IntegerField(default=100, help_text='Puntaje máximo del ejercicio')),
                ('tiempo_estimado_minutos', models.IntegerField(default=5, help_text='Tiempo estimado para completar (minutos)')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='core.modulo')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='core.objetivocurso')),
                ('rubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='core.rubricaevaluacion')),
            ],
            options={
                'verbose_name': 'Ejercicio Práctico',
                'verbose_name_plural': 'Ejercicios Prácticos',
                'ordering': ['modulo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pregunta', 'Pregunta'), ('reto', 'Reto'), ('ejercicio', 'Ejercicio'), ('examen', 'Examen'), ('consulta', 'Consulta General'), ('comprension', 'Pregunta de Comprensión')], default='consulta', max_length=30)),
                ('modalidad', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio'), ('mixto', 'Mixto')], default='texto', max_length=10)),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Duración de la interacción en segundos', null=True)),
                ('puntaje', models.IntegerField(blank=True, help_text='Puntaje obtenido (0-100)', null=True)),
                ('es_correcto', models.BooleanField(blank=True, help_text='Si la respuesta fue correcta', null=True)),
                ('respuesta_raw', models.TextField(blank=True, help_text='Respuesta original del estudiante')),
                ('feedback_generado', models.TextField(blank=True, help_text='Retroalimentación generada')),
                ('intent', models.CharField(blank=True, help_text='Intención detectada (si aplica NLU)', max_length=50)),
                ('municipio', models.CharField(blank=True, help_text='Municipio del estudiante', max_length=100)),
                ('departamento', models.CharField(blank=True, help_text='Departamento del estudiante', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional en formato JSON')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='core.estudiante')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Interacción Log',
                'verbose_name_plural': 'Logs de Interacciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estudiante', 'fecha'], name='core_intera_estudia_19d6fe_idx'), models.Index(fields=['curso', 'fecha'], name='core_intera_curso_i_3fd4d3_idx'), models.Index(fields=['municipio', 'fecha'], name='core_intera_municip_7ebab0_idx'), models.Index(fields=['modalidad', 'fecha'], name='core_intera_modalid_be6569_idx')],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.IntegerField(default=1, help_text='Número de intento')),
                ('respuesta_texto', models.TextField(blank=True, help_text='Respuesta en texto')),
                ('respuesta_numerica', models.DecimalField(blank=True, decimal_places=2, help_text='Respuesta numérica si aplica', max_digits=15, null=True)),
                ('respuesta_audio_url', models.URLField(blank=True, help_text='URL del audio de respuesta (si respondió por audio)', max_length=500)),
                ('puntaje_obtenido', models.IntegerField(default=0, help_text='Puntaje obtenido (0-100)')),
                ('es_correcto', models.BooleanField(default=False)),
                ('feedback_ia', models.TextField(blank=True, help_text='Retroalimentación generada por la IA')),
                ('evaluado_por_ia', models.BooleanField(default=False)),
                ('evaluado_por_docente', models.BooleanField(default=False)),
                ('tiempo_respuesta_segundos', models.IntegerField(blank=True, help_text='Tiempo que tardó en responder', null=True)),
                ('modalidad', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Audio'), ('mixto', 'Mixto')], default='texto', max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.ejerciciopractico')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_ejercicios', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Respuesta a Ejercicio',
                'verbose_name_plural': 'Respuestas a Ejercicios',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('ejercicio', 'estudiante', 'intento')},
            },
        ),
    ]
