# Generated by Django 5.2.9 on 2026-02-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_archivomodulo_options_estudiante_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupowhatsapp',
            name='capacidad_maxima',
        ),
        migrations.RemoveField(
            model_name='grupowhatsapp',
            name='link_invitacion',
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='error_detalle',
            field=models.TextField(blank=True, help_text='Detalle de error Twilio o del envío (código, mensaje, etc.)', null=True),
        ),
    ]
