# Generated by Django 5.2.9 on 2026-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_grupowhatsapp_capacidad_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='interaccionlog',
            name='departamento',
        ),
        migrations.AddField(
            model_name='certificado',
            name='archivo_imagen',
            field=models.ImageField(blank=True, help_text='Certificado en imagen (PNG/JPG)', null=True, upload_to='certificados/imagenes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='archivo_plantilla_imagen',
            field=models.ImageField(blank=True, help_text='🖼️ Sube una plantilla en formato imagen (PNG/JPG). Se personalizará con el nombre del estudiante.', null=True, upload_to='certificados/plantillas_imagenes/'),
        ),
        migrations.AddField(
            model_name='plantillacertificado',
            name='formato_certificado',
            field=models.CharField(choices=[('pdf', '📄 PDF'), ('imagen', '🖼️ Imagen (PNG/JPG)')], default='pdf', help_text='Formato de salida del certificado', max_length=10),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número del módulo (solo enteros positivos: 1, 2, 3, ...)'),
        ),
    ]
