# Generated by Django 5.2.9 on 2026-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_estudiante_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='imagen_portada_url',
            field=models.URLField(blank=True, help_text='URL de la imagen de portada del módulo', max_length=500, null=True),
        ),
    ]
