# Generated by Django 5.2.9 on 2026-02-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_modulo_imagen_portada_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacertificado',
            name='url_plantilla_imagen',
            field=models.URLField(blank=True, help_text='🔗 URL directa a una imagen de plantilla (PNG/JPG). Usa esto si prefieres alojar la imagen externamente.', max_length=500, null=True),
        ),
    ]
