# Generated by Django 5.2.9 on 2026-02-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_url_plantilla_imagen_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la campaña')),
                ('contenido', models.TextField(help_text='Texto que acompaña los botones SÍ/NO', verbose_name='Contenido del mensaje')),
                ('template_twilio_id', models.CharField(blank=True, help_text='El SID del template aprobado en Twilio (ej: HX123abc...)', max_length=255, null=True, verbose_name='Content SID de Twilio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('completada', 'Completada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Total enviados')),
                ('respuestas_si', models.IntegerField(default=0, verbose_name='Respuestas SÍ')),
                ('respuestas_no', models.IntegerField(default=0, verbose_name='Respuestas NO')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Campaña Única',
                'verbose_name_plural': 'Campañas Únicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCampanaUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('respuesta', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=5, verbose_name='Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('mensaje_sid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Message SID de Twilio')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.campanaunica', verbose_name='Campaña')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Respuesta Campaña Única',
                'verbose_name_plural': 'Respuestas Campañas Únicas',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('campana', 'numero_telefono')},
            },
        ),
    ]
