# Generated by Django 5.2.9 on 2026-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_campanaunica_respuestacampanaunica'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanaunica',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, help_text='Selecciona estudiantes específicos. Si dejas vacío, se enviará a TODOS los estudiantes activos del cliente.', to='core.estudiante', verbose_name='Estudiantes destinatarios'),
        ),
    ]
