# Generated by Django 5.2.9 on 2026-03-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_campana_unica_estudiantes_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectoB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número de teléfono del prospecto', max_length=20, unique=True, verbose_name='Teléfono WhatsApp')),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Contacto')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del prospecto', max_length=254, verbose_name='Email')),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa del prospecto', max_length=200, verbose_name='Empresa')),
                ('mensaje_original', models.TextField(blank=True, help_text='Primer mensaje que envió el prospecto', verbose_name='Mensaje Original')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_negociacion', 'En Negociación'), ('convertido', 'Convertido a Cliente'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado del Lead')),
                ('origen', models.CharField(choices=[('whatsapp_bot', 'Bot WhatsApp'), ('web', 'Sitio Web'), ('referido', 'Referido'), ('otro', 'Otro')], default='whatsapp_bot', max_length=20, verbose_name='Origen')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de Seguimiento')),
                ('esperando_email', models.BooleanField(default=False, help_text='Si el bot está esperando que el prospecto envíe su email', verbose_name='Esperando Email')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captura')),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True, verbose_name='Último Contacto')),
            ],
            options={
                'verbose_name': 'Prospecto B2B',
                'verbose_name_plural': '🏢 Prospectos B2B (Leads)',
                'ordering': ['-fecha_captura'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado_chat',
            field=models.CharField(choices=[('ESPERANDO_HABEAS_DATA', 'Esperando Habeas Data'), ('ESPERANDO_CEDULA', 'Esperando Cédula (2FA)'), ('CONFIRMANDO_DATOS', 'Confirmando Datos'), ('ACTIVO', 'Activo'), ('nuevo', 'Nuevo (legacy)'), ('esperando_tipo_doc', 'Esperando tipo doc (legacy)'), ('esperando_cedula_legacy', 'Esperando cédula (legacy)'), ('esperando_nombre', 'Esperando nombre (legacy)'), ('esperando_respuesta_modulo', 'Esperando respuesta módulo'), ('esperando_respuesta_tutor_ia', 'Esperando respuesta tutor IA'), ('esperando_respuesta_progreso', 'Esperando respuesta progreso'), ('esperando_seleccion_curso', 'Esperando selección curso'), ('completado', 'Completado (legacy)')], default='ESPERANDO_HABEAS_DATA', help_text='Estado actual en la máquina de estados B2B del onboarding', max_length=50, verbose_name='Estado del Chat'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='preguntas_ia_restantes',
            field=models.IntegerField(default=3, help_text='Máximo de preguntas libres a la IA por módulo (se resetea al completar módulo)', verbose_name='Preguntas IA Restantes'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rango_edad',
            field=models.CharField(blank=True, choices=[('18-30', '18 a 30 años'), ('31-50', '31 a 50 años'), ('50+', 'Mayor de 50 años')], help_text='Rango de edad del estudiante', max_length=10, verbose_name='Rango de Edad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='region',
            field=models.CharField(blank=True, help_text='Región geográfica (Ej: Zona Norte, Magdalena Medio)', max_length=100, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(help_text='Número de identificación único (limpio, sin puntos ni espacios)', max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Organización/Empresa B2B a la que pertenece este estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='core.cliente', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_onboarding',
            field=models.CharField(default='nuevo', help_text='nuevo, esperando_tipo_doc, esperando_cedula, esperando_nombre, esperando_respuesta_modulo, completado', max_length=50, verbose_name='Estado Onboarding (Legacy)'),
        ),
    ]
