# Generated by Django 5.2.9 on 2026-03-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_prospectob2b_estudiante_estado_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='departamento',
            field=models.CharField(blank=True, help_text='Departamento de Colombia (Ej: Antioquia, Cundinamarca)', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NR', 'No Reporta')], default='', help_text='Género del estudiante', max_length=2, verbose_name='Género'),
        ),
    ]
