# Generated by Django 5.2.9 on 2026-03-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_departamento_genero_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_chat',
            field=models.CharField(choices=[('ESPERANDO_HABEAS_DATA', 'Esperando Habeas Data'), ('ESPERANDO_CEDULA', 'Esperando Cédula (2FA)'), ('CONFIRMANDO_DATOS', 'Confirmando Datos'), ('ESPERANDO_AYUDA_MODIFICAR', 'Esperando Ayuda Modificar Datos'), ('ACTIVO', 'Activo'), ('nuevo', 'Nuevo (legacy)'), ('esperando_tipo_doc', 'Esperando tipo doc (legacy)'), ('esperando_cedula_legacy', 'Esperando cédula (legacy)'), ('esperando_nombre', 'Esperando nombre (legacy)'), ('esperando_respuesta_modulo', 'Esperando respuesta módulo'), ('esperando_respuesta_tutor_ia', 'Esperando respuesta tutor IA'), ('esperando_respuesta_progreso', 'Esperando respuesta progreso'), ('esperando_seleccion_curso', 'Esperando selección curso'), ('completado', 'Completado (legacy)')], default='ESPERANDO_HABEAS_DATA', help_text='Estado actual en la máquina de estados B2B del onboarding', max_length=50, verbose_name='Estado del Chat'),
        ),
    ]
