# Generated by Django 5.2.9 on 2026-03-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_add_estado_ayuda_modificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='respuestas_no',
            field=models.IntegerField(default=0, verbose_name='Respuestas NO'),
        ),
        migrations.AddField(
            model_name='campana',
            name='respuestas_si',
            field=models.IntegerField(default=0, verbose_name='Respuestas SÍ'),
        ),
        migrations.AddField(
            model_name='campana',
            name='template_twilio_id',
            field=models.CharField(blank=True, help_text='SID del template aprobado en Twilio (ej: HX123abc...). Si se llena, se usa en vez de la plantilla Django.', max_length=255, null=True, verbose_name='Content SID de Twilio'),
        ),
        migrations.AddField(
            model_name='campana',
            name='total_enviados',
            field=models.IntegerField(default=0, verbose_name='Total enviados'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plantilla'),
        ),
    ]
