# Generated by Django 5.2.9 on 2026-03-02 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_unify_campana_add_template_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjerecompensa',
            name='atendido_por',
            field=models.CharField(blank=True, help_text='Miembro del equipo eki que procesó el canje', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas para uso interno de eki (no visibles para el cliente)', verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Si es para un cliente específico. Dejar vacío = curso general de eki disponible para todos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.cliente', verbose_name='Cliente Específico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_chat',
            field=models.CharField(choices=[('ESPERANDO_HABEAS_DATA', 'Esperando Habeas Data'), ('ESPERANDO_CEDULA', 'Esperando Cédula (2FA)'), ('CONFIRMANDO_DATOS', 'Confirmando Datos'), ('ESPERANDO_AYUDA_MODIFICAR', 'Esperando Ayuda Modificar Datos'), ('ESPERANDO_CORRECCION_DATOS', 'Esperando Corrección Datos'), ('ACTIVO', 'Activo'), ('nuevo', 'Nuevo (legacy)'), ('esperando_tipo_doc', 'Esperando tipo doc (legacy)'), ('esperando_cedula_legacy', 'Esperando cédula (legacy)'), ('esperando_nombre', 'Esperando nombre (legacy)'), ('esperando_respuesta_modulo', 'Esperando respuesta módulo'), ('esperando_respuesta_tutor_ia', 'Esperando respuesta tutor IA'), ('esperando_respuesta_progreso', 'Esperando respuesta progreso'), ('esperando_seleccion_curso', 'Esperando selección curso'), ('completado', 'Completado (legacy)')], default='ESPERANDO_HABEAS_DATA', help_text='Estado actual en la máquina de estados B2B del onboarding', max_length=50, verbose_name='Estado del Chat'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Si es para un cliente específico. Dejar vacío = plantilla general de eki', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_certificados', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='texto_superior',
            field=models.CharField(default='eki - Educación Agrícola', help_text='Texto en la parte superior', max_length=200),
        ),
    ]
