# Generated by Django 5.2.9 on 2026-03-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_estado_correccion_datos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudsoporte',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Soporte y PQRS', 'verbose_name_plural': '🆘 Soporte y PQRS'},
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del estudiante en años', null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='asunto',
            field=models.CharField(blank=True, help_text='Asunto de la solicitud (opcional para soporte, recomendado para PQRS)', max_length=200, verbose_name='Asunto'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='calificacion',
            field=models.IntegerField(blank=True, help_text='Del 1 al 5, otorgada por el estudiante', null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='comentario_calificacion',
            field=models.TextField(blank=True, verbose_name='Comentario de Calificación'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='curso_relacionado',
            field=models.ForeignKey(blank=True, help_text='Curso relacionado con la solicitud (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso Relacionado'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='tipo_solicitud',
            field=models.CharField(choices=[('soporte', '🆘 Soporte (Botón de Pánico)'), ('peticion', '📋 Petición'), ('queja', '😤 Queja'), ('reclamo', '📢 Reclamo'), ('sugerencia', '💡 Sugerencia'), ('felicitacion', '🌟 Felicitación')], default='soporte', help_text='Tipo: soporte técnico o PQRS', max_length=20, verbose_name='Tipo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rango_edad',
            field=models.CharField(blank=True, choices=[('18-30', '18 a 30 años'), ('31-50', '31 a 50 años'), ('50+', 'Mayor de 50 años')], help_text='Rango de edad del estudiante (se calcula automáticamente si se proporciona edad)', max_length=10, verbose_name='Rango de Edad'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['tipo_solicitud', 'estado'], name='core_solici_tipo_so_61e2c9_idx'),
        ),
    ]
