# Generated by Django 5.2.9 on 2026-03-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_solicitudsoporte_options_estudiante_edad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador único (ej: Manual_Tomates_v1, FAQ_Café)', max_length=200, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(help_text='Formatos soportados: .pdf, .docx, .txt', upload_to='documentos_rag/%Y/%m/', verbose_name='Archivo (PDF, DOCX, TXT)')),
                ('tipo', models.CharField(choices=[('contenido', 'Contenido del Curso'), ('manual', 'Manual / Documentación'), ('faq', 'Preguntas Frecuentes'), ('guia', 'Guía Práctica'), ('normativa', 'Normativa / Regulación')], default='contenido', max_length=20, verbose_name='Tipo de documento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de indexar'), ('indexado', 'Indexado en RAG'), ('error', 'Error al indexar')], default='pendiente', max_length=20, verbose_name='Estado RAG')),
                ('chunks_indexados', models.IntegerField(default=0, help_text='Cantidad de fragmentos indexados en la BD vectorial', verbose_name='Chunks indexados')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del contenido del documento', verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_indexado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(help_text='Curso al que pertenece este documento. Los agentes IA SOLO verán documentos de su curso.', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_rag', to='core.curso', verbose_name='Curso')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento RAG',
                'verbose_name_plural': '📚 Documentos RAG (Base de Conocimiento IA)',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['curso', 'estado'], name='core_docume_curso_i_f65e8a_idx')],
                'unique_together': {('curso', 'nombre')},
            },
        ),
    ]
