# Generated by Django 5.2.9 on 2026-03-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_documentorag'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombre_agente_asistente',
            field=models.CharField(blank=True, default='', help_text='Nombre personalizado para la agente asistente (por defecto: María). Ej: Laura, Andrea', max_length=100, verbose_name='Nombre de la Asistente (IA)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_agente_tutor',
            field=models.CharField(blank=True, default='', help_text='Nombre personalizado para el agente tutor/profesor (por defecto: Gerónimo). Ej: Carlos, Sofía', max_length=100, verbose_name='Nombre del Profesor (Tutor IA)'),
        ),
    ]
