# Generated by Django 5.2.9 on 2026-03-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_agent_names_to_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='archivo_imagen',
            field=models.ImageField(blank=True, help_text='Certificado en imagen (PNG/JPG)', null=True, upload_to='Certificadosestudiantes/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Certificado en PDF', null=True, upload_to='Certificadosestudiantes/'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='texto_superior',
            field=models.CharField(default='eki - Soluciones Educativas', help_text='Texto en la parte superior', max_length=200),
        ),
    ]
