# Generated by Django 5.2.9 on 2026-03-10 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_plantillacertificado_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='preguntas_ejemplo_ia',
            field=models.TextField(blank=True, default='', help_text='Preguntas ejemplo que la IA usará como referencia para generar la pregunta final de recuperación. Una pregunta por línea.', verbose_name='Preguntas ejemplo para IA'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='curso_destino',
            field=models.ForeignKey(blank=True, help_text='Curso al que se inscribirán los estudiantes al completar el onboarding de esta campaña.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_curso', to='core.curso', verbose_name='Curso destino'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='es_campana_curso',
            field=models.BooleanField(default=False, help_text='Si está activado, al enviar la campaña los estudiantes entrarán al flujo de habeas data → verificación → curso.', verbose_name='¿Es campaña de inicio de curso?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_agente_asistente',
            field=models.CharField(blank=True, default='', help_text='Nombre personalizado para la agente asistente (por defecto: María). Ej: Laura, Andrea', max_length=100, verbose_name='Nombre de la Asistente (IA)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_agente_tutor',
            field=models.CharField(blank=True, default='', help_text='Nombre personalizado para el agente tutor/profesor (por defecto: Gerónimo). Ej: Carlos, Sofía', max_length=100, verbose_name='Nombre del Profesor (Tutor IA)'),
        ),
    ]
