# Generated by Django 5.2.9 on 2026-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_campanab2b'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivomodulo',
            options={'ordering': ['modulo', 'orden', 'id'], 'verbose_name': 'Archivo Multimedia', 'verbose_name_plural': '📁 Archivos Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='campana',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': '📣 Campañas'},
        ),
        migrations.AlterModelOptions(
            name='campanaunica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Campaña Única', 'verbose_name_plural': '📩 Campañas Únicas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': '🏢 Clientes (Organizaciones)'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': '📖 Cursos'},
        ),
        migrations.AlterModelOptions(
            name='ejerciciopractico',
            options={'ordering': ['modulo', 'orden'], 'verbose_name': 'Ejercicio Práctico', 'verbose_name_plural': '📝 Ejercicios Prácticos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': '🎓 Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': '📋 Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='interaccionlog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Interacción Log', 'verbose_name_plural': '📝 Logs de Interacciones'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['curso', 'numero'], 'verbose_name': 'Módulo', 'verbose_name_plural': '📦 Módulos'},
        ),
        migrations.AlterModelOptions(
            name='modulocompletado',
            options={'verbose_name': 'Módulo Completado', 'verbose_name_plural': '✅ Módulos Completados'},
        ),
        migrations.AlterModelOptions(
            name='objetivocurso',
            options={'ordering': ['curso', 'orden'], 'verbose_name': 'Objetivo de Curso', 'verbose_name_plural': '🎯 Objetivos de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': '📝 Plantillas de Mensaje'},
        ),
        migrations.AlterModelOptions(
            name='preguntaexamen',
            options={'ordering': ['examen', 'numero'], 'verbose_name': 'Pregunta de Examen', 'verbose_name_plural': '❔ Preguntas de Examen'},
        ),
        migrations.AlterModelOptions(
            name='preguntamodulo',
            options={'ordering': ['modulo', 'id'], 'verbose_name': 'Pregunta de Módulo', 'verbose_name_plural': '❓ Preguntas de Módulos'},
        ),
        migrations.AlterModelOptions(
            name='progresoestudiante',
            options={'verbose_name': 'Progreso de Estudiante', 'verbose_name_plural': '📊 Progreso de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='respuestacampanaunica',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Respuesta Campaña Única', 'verbose_name_plural': '📬 Respuestas Campañas Únicas'},
        ),
        migrations.AlterModelOptions(
            name='respuestaejercicio',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Respuesta a Ejercicio', 'verbose_name_plural': '✍️ Respuestas a Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='resultadoexamen',
            options={'verbose_name': 'Resultado de Examen', 'verbose_name_plural': '🏅 Resultados de Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='rubricaevaluacion',
            options={'verbose_name': 'Rúbrica de Evaluación', 'verbose_name_plural': '📏 Rúbricas de Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='temacampana',
            options={'ordering': ['nombre'], 'verbose_name': 'Tema de Campaña', 'verbose_name_plural': '🏷️ Temas de Campaña'},
        ),
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de WhatsApp', 'verbose_name_plural': '💬 Historial WhatsApp'},
        ),
        migrations.AlterField(
            model_name='campanab2b',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campanab2b',
            name='url_media',
            field=models.URLField(blank=True, help_text='URL pública del PDF o archivo a adjuntar. Debe ser accesible públicamente.', max_length=500, verbose_name='URL del PDF/Media (opcional)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_chat',
            field=models.CharField(choices=[('ESPERANDO_HABEAS_DATA', 'Esperando Habeas Data'), ('ESPERANDO_CEDULA', 'Esperando Cédula (2FA)'), ('CONFIRMANDO_DATOS', 'Confirmando Datos'), ('ESPERANDO_AYUDA_MODIFICAR', 'Esperando Ayuda Modificar Datos'), ('ESPERANDO_CORRECCION_DATOS', 'Esperando Corrección Datos'), ('ACTIVO', 'Activo'), ('nuevo', 'Nuevo (legacy)'), ('esperando_tipo_doc', 'Esperando tipo doc (legacy)'), ('esperando_cedula_legacy', 'Esperando cédula (legacy)'), ('esperando_nombre', 'Esperando nombre (legacy)'), ('esperando_respuesta_modulo', 'Esperando respuesta módulo'), ('esperando_respuesta_tutor_ia', 'Esperando respuesta tutor IA'), ('esperando_respuesta_progreso', 'Esperando respuesta progreso'), ('esperando_seleccion_curso', 'Esperando selección curso'), ('esperando_respuesta_asistente', 'Esperando respuesta asistente Darío'), ('esperando_respuesta_reto', 'Esperando respuesta reto facilitador'), ('curso_finalizado', 'Curso finalizado (sin interacción)'), ('completado', 'Completado (legacy)')], default='ESPERANDO_HABEAS_DATA', help_text='Estado actual en la máquina de estados B2B del onboarding', max_length=50, verbose_name='Estado del Chat'),
        ),
    ]
