# Generated by Django 5.2.9 on 2026-03-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_archivomodulo_options_alter_campana_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivomodulo',
            options={'ordering': ['modulo', 'orden', 'id'], 'verbose_name': 'Archivo Multimedia', 'verbose_name_plural': 'Archivos Multimedia'},
        ),
        migrations.AlterModelOptions(
            name='campana',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='campanab2b',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Campaña B2B', 'verbose_name_plural': 'Campañas B2B'},
        ),
        migrations.AlterModelOptions(
            name='campanaunica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Campaña Única', 'verbose_name_plural': 'Campañas Únicas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes (Organizaciones)'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='documentorag',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento RAG', 'verbose_name_plural': 'Documentos RAG (Base de Conocimiento IA)'},
        ),
        migrations.AlterModelOptions(
            name='ejerciciopractico',
            options={'ordering': ['modulo', 'orden'], 'verbose_name': 'Ejercicio Práctico', 'verbose_name_plural': 'Ejercicios Prácticos'},
        ),
        migrations.AlterModelOptions(
            name='envioprogramado',
            options={'ordering': ['-fecha_programada'], 'verbose_name': 'Envío Programado', 'verbose_name_plural': 'Envíos Programados'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='grupoestudiantes',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Grupo de Estudiantes', 'verbose_name_plural': 'Grupos de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='grupowhatsapp',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Grupo de WhatsApp', 'verbose_name_plural': 'Grupos de WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='interaccionlog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Interacción Log', 'verbose_name_plural': 'Logs de Interacciones'},
        ),
        migrations.AlterModelOptions(
            name='invitaciongrupo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Invitación a Grupo', 'verbose_name_plural': 'Invitaciones a Grupos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['curso', 'numero'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='modulocompletado',
            options={'verbose_name': 'Módulo Completado', 'verbose_name_plural': 'Módulos Completados'},
        ),
        migrations.AlterModelOptions(
            name='objetivocurso',
            options={'ordering': ['curso', 'orden'], 'verbose_name': 'Objetivo de Curso', 'verbose_name_plural': 'Objetivos de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='plantilla',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Plantilla de Mensaje', 'verbose_name_plural': 'Plantillas de Mensaje'},
        ),
        migrations.AlterModelOptions(
            name='pqrs',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'PQRS', 'verbose_name_plural': 'PQRS (Peticiones/Quejas/Reclamos/Sugerencias)'},
        ),
        migrations.AlterModelOptions(
            name='preguntaexamen',
            options={'ordering': ['examen', 'numero'], 'verbose_name': 'Pregunta de Examen', 'verbose_name_plural': 'Preguntas de Examen'},
        ),
        migrations.AlterModelOptions(
            name='preguntamodulo',
            options={'ordering': ['modulo', 'id'], 'verbose_name': 'Pregunta de Módulo', 'verbose_name_plural': 'Preguntas de Módulos'},
        ),
        migrations.AlterModelOptions(
            name='progresoestudiante',
            options={'verbose_name': 'Progreso de Estudiante', 'verbose_name_plural': 'Progreso de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='prospectob2b',
            options={'ordering': ['-fecha_captura'], 'verbose_name': 'Prospecto B2B', 'verbose_name_plural': 'Prospectos B2B (Leads)'},
        ),
        migrations.AlterModelOptions(
            name='respuestacampanaunica',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Respuesta Campaña Única', 'verbose_name_plural': 'Respuestas Campañas Únicas'},
        ),
        migrations.AlterModelOptions(
            name='respuestaejercicio',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Respuesta a Ejercicio', 'verbose_name_plural': 'Respuestas a Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='resultadoexamen',
            options={'verbose_name': 'Resultado de Examen', 'verbose_name_plural': 'Resultados de Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='rubricaevaluacion',
            options={'verbose_name': 'Rúbrica de Evaluación', 'verbose_name_plural': 'Rúbricas de Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='solicitudsoporte',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Soporte y PQRS', 'verbose_name_plural': 'Soporte y PQRS'},
        ),
        migrations.AlterModelOptions(
            name='temacampana',
            options={'ordering': ['nombre'], 'verbose_name': 'Tema de Campaña', 'verbose_name_plural': 'Temas de Campaña'},
        ),
        migrations.AlterModelOptions(
            name='whatsapplog',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de WhatsApp', 'verbose_name_plural': 'Historial WhatsApp'},
        ),
    ]
