# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_archivomodulo_options_alter_campana_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dias_espera_entre_modulos',
            field=models.IntegerField(
                default=0,
                help_text='0 = flujo libre. >0 bloquea avance hasta cumplir días entre módulos.',
                verbose_name='Días de espera entre módulos'
            ),
        ),
        migrations.AddField(
            model_name='progresoestudiante',
            name='fecha_ultimo_avance',
            field=models.DateTimeField(
                blank=True,
                help_text='Se actualiza cuando el estudiante completa/avanza de módulo.',
                null=True,
                verbose_name='Fecha último avance'
            ),
        ),
        migrations.CreateModel(
            name='AliadoEmpleabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('vacantes_activas', models.BooleanField(default=True, verbose_name='Vacantes activas')),
                ('codigo_secreto', models.CharField(max_length=120, verbose_name='Código secreto')),
                ('indicacion_sector', models.CharField(blank=True, default='', help_text='Ej: costado oriental del parque principal', max_length=200, verbose_name='Indicación de sector')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional. Si se define, solo aplica para estudiantes de ese cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliados_empleabilidad', to='core.cliente', verbose_name='Cliente asociado')),
            ],
            options={
                'verbose_name': 'Aliado de Empleabilidad',
                'verbose_name_plural': 'Aliados de Empleabilidad',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaFinalCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(verbose_name='Pregunta abierta final')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_abierta_final', to='core.curso')),
            ],
            options={
                'verbose_name': 'Pregunta Abierta Final',
                'verbose_name_plural': 'Preguntas Abiertas Finales',
            },
        ),
        migrations.CreateModel(
            name='RespuestaAbiertaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(verbose_name='Respuesta del estudiante')),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de calificar'), ('calificada', 'Calificada')], default='pendiente', max_length=20)),
                ('calificacion', models.IntegerField(blank=True, null=True, verbose_name='Calificación (0-100)')),
                ('retroalimentacion', models.TextField(blank=True, default='', verbose_name='Retroalimentación facilitadora')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('calificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_preguntas_abiertas', to='auth.user')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_abiertas_finales', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_abiertas_finales', to='core.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.preguntaabiertafinalcurso')),
                ('progreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_abiertas_finales', to='core.progresoestudiante')),
            ],
            options={
                'verbose_name': 'Respuesta Abierta Final',
                'verbose_name_plural': 'Respuestas Abiertas Finales',
                'ordering': ['-fecha_respuesta'],
                'unique_together': {('pregunta', 'estudiante')},
            },
        ),
    ]
