# Generated by Django 5.2.9 on 2026-03-26 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_cliente_feature_windows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaabiertafinalcurso',
            options={'ordering': ['curso', 'orden', 'id'], 'verbose_name': 'Pregunta Abierta Final', 'verbose_name_plural': 'Preguntas Abiertas Finales'},
        ),
        migrations.AddField(
            model_name='curso',
            name='habilitar_pregunta_abierta_final',
            field=models.BooleanField(default=False, help_text='Si está activado, este curso puede mostrar preguntas abiertas finales (hasta 3).', verbose_name='Habilitar Pregunta Abierta Final'),
        ),
        migrations.AddField(
            model_name='preguntaabiertafinalcurso',
            name='orden',
            field=models.PositiveSmallIntegerField(default=1, help_text='Orden de la pregunta en el cierre (1 a 3).', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_chat',
            field=models.CharField(choices=[('ESPERANDO_HABEAS_DATA', 'Esperando Habeas Data'), ('ESPERANDO_CEDULA', 'Esperando Cédula (2FA)'), ('CONFIRMANDO_DATOS', 'Confirmando Datos'), ('ESPERANDO_AYUDA_MODIFICAR', 'Esperando Ayuda Modificar Datos'), ('ESPERANDO_CORRECCION_DATOS', 'Esperando Corrección Datos'), ('ACTIVO', 'Activo'), ('nuevo', 'Nuevo (legacy)'), ('esperando_tipo_doc', 'Esperando tipo doc (legacy)'), ('esperando_cedula_legacy', 'Esperando cédula (legacy)'), ('esperando_nombre', 'Esperando nombre (legacy)'), ('esperando_respuesta_modulo', 'Esperando respuesta módulo'), ('esperando_respuesta_tutor_ia', 'Esperando respuesta tutor IA'), ('esperando_respuesta_progreso', 'Esperando respuesta progreso'), ('esperando_seleccion_curso', 'Esperando selección curso'), ('esperando_respuesta_asistente', 'Esperando respuesta asistente Darío'), ('esperando_respuesta_reto', 'Esperando respuesta reto facilitador'), ('esperando_codigo_empleabilidad', 'Esperando código de empleabilidad'), ('esperando_respuesta_pregunta_abierta_final', 'Esperando respuesta pregunta abierta final'), ('curso_finalizado', 'Curso finalizado (sin interacción)'), ('completado', 'Completado (legacy)')], default='ESPERANDO_HABEAS_DATA', help_text='Estado actual en la máquina de estados B2B del onboarding', max_length=50, verbose_name='Estado del Chat'),
        ),
        migrations.AlterField(
            model_name='preguntaabiertafinalcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_abiertas_finales', to='core.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='preguntaabiertafinalcurso',
            unique_together={('curso', 'orden')},
        ),
    ]
