# Generated by Django 5.2.9 on 2026-04-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_rename_empleabilidad_rag_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoragcomercial',
            name='canal',
            field=models.CharField(choices=[('bot_comercial', 'Bot Comercial WhatsApp'), ('agro_nexo', 'Agro Nexo WhatsApp')], default='bot_comercial', max_length=40, verbose_name='Canal comercial'),
        ),
        migrations.AlterField(
            model_name='documentoragcomercial',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto / Catálogo'), ('precio', 'Precio / Lista comercial'), ('informe_tecnico', 'Informe técnico (ICA / ensayos)'), ('faq', 'Preguntas frecuentes comerciales'), ('politica', 'Políticas comerciales'), ('promo', 'Promociones'), ('general', 'Información general comercial')], default='producto', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
