# Generated by Django 5.2.9 on 2026-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_cliente_enlace_habeas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias_espera_entre_modulos',
            field=models.IntegerField(default=0, help_text='0 = flujo libre. >0 bloquea avance hasta cumplir días entre módulos. Para el mismo curso en varias empresas con ritmos distintos, usar Configuración drip en el admin del Cliente.', verbose_name='Días de espera entre módulos'),
        ),
    ]
