# Generated by Django 5.2.9 on 2026-04-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_curso_dias_espera_entre_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre_bot',
            field=models.CharField(blank=True, default='Nati', help_text='Nombre con el que se presenta el bot comercial al productor (default: Nati). Ej: Nati, Aliada, Sofi.', max_length=40, verbose_name='Nombre del Bot Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='system_prompt_extra',
            field=models.TextField(blank=True, default='', help_text='Instrucciones específicas de este cliente que se concatenan al system prompt de Nati. Útil para tono, productos prioritarios o restricciones por marca.', verbose_name='Instrucciones extra para el Bot Comercial'),
        ),
    ]
