# Generated by Django 5.2.9 on 2026-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_cliente_nombre_bot_cliente_system_prompt_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tiene_formulario_gei',
            field=models.BooleanField(default=False, help_text='Si está activo, al completar el módulo disparador configurado en Formulario → Tipos de formulario se inicia la recolección de datos GEI por WhatsApp. Si está inactivo, ningún flujo se dispara aunque exista el TipoFormulario.', verbose_name='¿Activa formulario GEI al completar el último módulo?'),
        ),
    ]
