# Generated by Django 5.2.9 on 2026-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_curso_tiene_formulario_gei'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsoporte',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', '— Sin clasificar'), ('acceso', '🔑 Acceso (login, cédula, número)'), ('contenido', '📚 Contenido (módulo, video, examen)'), ('tecnico', '🛠️ Técnico (errores del sistema)'), ('otro', '❓ Otro')], default='', help_text='Clasificación automática del agente PQRS (acceso, contenido, técnico, otro).', max_length=20, verbose_name='Categoría PQRS'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='resuelto_por_agente',
            field=models.BooleanField(default=False, help_text='True si el agente PQRS resolvió en primer nivel; False si quedó escalado.', verbose_name='Resuelto por agente IA'),
        ),
    ]
