# Generated by Django 5.2.9 on 2026-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_solicitudsoporte_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sid_habeas_data_global', models.CharField(blank=True, default='', help_text='Content SID (HX...) de la plantilla Twilio aprobada para el Habeas Data por defecto. Se usa cuando el cliente no tiene su propio Content SID configurado.', max_length=64, verbose_name='Habeas Data — Plantilla Twilio general (Content SID)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='content_sid_habeas_data_twilio',
            field=models.CharField(blank=True, default='', help_text='Opcional: Content SID (HX...) de la plantilla Twilio aprobada para el Habeas Data de ESTE cliente. Si se deja vacío, se usa la plantilla global configurada en "Configuración Global > Habeas Data — Plantilla Twilio general".', max_length=64, verbose_name='Habeas Data — Plantilla Twilio (Content SID del cliente)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='usar_agentes_ia',
            field=models.BooleanField(default=True, help_text='Si está activo, al completar el módulo 3 y el último módulo del curso se dispara una pausa con el asistente Darío (resuelve dudas) y luego un reto evaluado por la facilitadora Claudia (otorga puntos). Si está inactivo, el curso es lineal: examen → siguiente módulo, sin retos. Útil para cursos cortos, formularios o pilotos donde no se quiere la capa de IA.', verbose_name='¿Usar retos con agentes IA (Darío + Claudia)?'),
        ),
    ]
