# Generated by Django 5.2.9 on 2026-04-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_configuracionglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='content_sid_habeas_data_twilio',
            field=models.CharField(blank=True, default='', help_text='Opcional: Content SID (HX...) del template de Habeas Data para ESTE cliente. Si se deja vacío, el sistema usa el template global de eki configurado en "Configuración Global".', max_length=64, verbose_name='Habeas Data Template (Twilio Content SID por cliente)'),
        ),
        migrations.CreateModel(
            name='SesionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=30)),
                ('historial_mensajes', models.JSONField(blank=True, default=list, help_text='Lista de mensajes [{"role": "...", "content": "..."}]. Máximo 10 turnos (20 mensajes).')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(auto_now=True, db_index=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_comerciales', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Sesión comercial',
                'verbose_name_plural': 'Sesiones comerciales',
                'ordering': ['-fecha_ultimo_mensaje'],
                'indexes': [models.Index(fields=['telefono', '-fecha_ultimo_mensaje'], name='core_sesion_telefon_612642_idx'), models.Index(fields=['cliente', '-fecha_ultimo_mensaje'], name='core_sesion_cliente_ccbf6e_idx')],
            },
        ),
    ]
