# Generated by Django 5.2.9 on 2026-05-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_cliente_content_sid_habeas_data_twilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoestudiante',
            name='esperando_respuesta_evaluacion_paso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresoestudiante',
            name='paso_actual_modulo',
            field=models.PositiveIntegerField(default=1, help_text='Índice 1-based del siguiente paso a entregar con *listo* (solo si el módulo tiene pasos activos).'),
        ),
        migrations.CreateModel(
            name='PasoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('contenido', 'Contenido'), ('evaluacion_opciones', 'Evaluación (opciones)'), ('evaluacion_abierta', 'Evaluación (abierta)'), ('reto', 'Reto'), ('entrega', 'Entrega')], default='contenido', max_length=32)),
                ('contenido', models.TextField(blank=True, help_text='Texto del paso (instrucciones, contexto)')),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('opciones_json', models.JSONField(blank=True, help_text='Para evaluación opciones: {"A":"...","B":"...","correcta":"A"}', null=True)),
                ('respuesta_correcta', models.CharField(blank=True, help_text='Letra correcta (A-D) si no usás solo opciones_json.correcta', max_length=10)),
                ('feedback_correcto', models.TextField(blank=True)),
                ('feedback_incorrecto', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_listo_para_avanzar', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Paso de módulo',
                'verbose_name_plural': 'Pasos de módulo',
                'ordering': ['modulo', 'orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='progresoestudiante',
            name='paso_evaluacion_paso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.pasomodulo'),
        ),
        migrations.AddConstraint(
            model_name='pasomodulo',
            constraint=models.UniqueConstraint(fields=('modulo', 'orden'), name='uniq_pasomodulo_modulo_orden'),
        ),
    ]
