# Generated by Django 5.2.9 on 2026-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_pasomodulo_progreso_pasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='facilitador_checkpoint',
            field=models.CharField(choices=[('auto', 'Heredar regla del curso (mód. 3, penúltimos, etc.)'), ('si', 'Sí: al cerrar este módulo, compañero + facilitadora'), ('no', 'No: nunca checkpoint IA al cerrar este módulo')], default='auto', help_text='Solo aplica si el curso tiene agentes IA activos. Define si al terminar este módulo entra el flujo Darío/facilitadora o se salta, independiente del número de módulo.', max_length=10, verbose_name='Checkpoint facilitadora'),
        ),
    ]
