# Generated by Django 5.2.9 on 2026-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_modulo_facilitador_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='modo_entrega',
            field=models.CharField(choices=[('auto', 'Automático (hereda: pasos si existen, legacy si no)'), ('legacy', 'Todo de una vez (contenido + multimedia completo)'), ('pasos', 'Por pasos con "listo" (requiere pasos configurados)')], default='auto', help_text='Automático: usa pasos si existen, legacy si no. Legacy: envía todo el módulo de una vez aunque haya pasos internos cargados. Pasos: un paso por *listo*; sin pasos activos el admin muestra aviso y el estudiante recibe un mensaje seguro.', max_length=10, verbose_name='Modo de entrega'),
        ),
    ]
