# Generated by Django 5.2.9 on 2026-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_seccionmodulo_y_secciones_por_listo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasomodulo',
            options={'ordering': ['modulo', 'orden', 'id'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos'},
        ),
        migrations.AlterField(
            model_name='modulo',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número de orden del módulo en el curso (enteros ≥ 0: 0 = intro/bienvenida, luego 1, 2, 3…)'),
        ),
        migrations.AlterField(
            model_name='pasomodulo',
            name='opciones_json',
            field=models.JSONField(blank=True, help_text='Solo para tipo «Evaluación (opciones)». JSON con letras A–D y la correcta. Ejemplo: {"A": "Opción uno", "B": "Opción dos", "C": "Opción tres", "correcta": "B"} También acepta respuesta_correcta en vez de correcta. Si vas a mapear filas de planilla (001, 005.1…): usá orden entero secuencial (1,2,3…); el título puede ser «005.1 Pregunta…».', null=True),
        ),
    ]
