# Generated by Django 5.2.9 on 2026-05-09 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_modulo_numero_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorag',
            name='archivo',
            field=models.FileField(help_text='Formatos soportados: .pdf, .docx, .txt, .xlsx, .xlsm (Excel; listas de precios)', upload_to='documentos_rag/%Y/%m/', verbose_name='Archivo (PDF, DOCX, TXT, XLSX)'),
        ),
        migrations.AlterField(
            model_name='documentoragcomercial',
            name='archivo',
            field=models.FileField(help_text='Formatos soportados: .pdf, .docx, .txt, .xlsx, .xlsm (Excel; listas de precios)', upload_to='documentos_rag_comercial/%Y/%m/', verbose_name='Archivo (PDF, DOCX, TXT, XLSX)'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='secciones_por_listo',
            field=models.PositiveSmallIntegerField(default=1, help_text='Reservado: históricamente permitía agrupar varias secciones en un solo *listo*. Ahora siempre se pide *listo* entre secciones (un bloque a la vez) para asegurar que el estudiante sigue el material. Dentro de una misma sección pueden enviarse varios pasos seguidos.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Secciones por *listo*'),
        ),
    ]
