# Generated by Django 5.2.9 on 2026-05-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_pasomodulo_eval_campos_y_seccion_ayuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='habilitado_desde',
            field=models.DateTimeField(blank=True, help_text='Opcional. Antes de esta fecha y hora ningún estudiante puede recibir este módulo al avanzar desde el anterior. Para una empresa concreta, creá una fila en el cliente: «Habilitación de módulos por cliente» (sustituye esto).', null=True, verbose_name='Disponible desde (calendario global)'),
        ),
        migrations.CreateModel(
            name='HabilitacionModuloDripCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado_desde', models.DateTimeField(help_text='Hora local del servidor según TIME_ZONE; el estudiante no recibe este módulo antes de este instante.', verbose_name='Disponible desde')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones_modulo_drip', to='core.cliente', verbose_name='Cliente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones_modulo_por_cliente', to='core.curso', verbose_name='Curso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones_por_cliente', to='core.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Habilitación de módulo (cliente × curso × módulo)',
                'verbose_name_plural': 'Habilitaciones de módulos por cliente',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'curso', 'modulo'), name='uniq_habilitacion_drip_cliente_curso_modulo')],
            },
        ),
    ]
