# Generated by Django 5.2.9 on 2026-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_solicitudsoporte_preguntas_realizadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextoagrosession',
            options={'verbose_name': 'Contexto agronómico (Nat)', 'verbose_name_plural': 'Contextos agronómicos (Nat)'},
        ),
        migrations.AlterModelOptions(
            name='metametricanati',
            options={'verbose_name': 'Meta métrica Nat', 'verbose_name_plural': 'Metas métricas Nat'},
        ),
        migrations.RenameIndex(
            model_name='eventoia',
            new_name='core_evento_created_1d3a44_idx',
            old_name='core_evento_created_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoia',
            new_name='core_evento_trace_i_1d3afb_idx',
            old_name='core_evento_trace_created_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_bot',
            field=models.CharField(blank=True, default='Nati', help_text='Nombre con el que se presenta el bot comercial al productor (default en código: Nat). Ej: Nat, Aliada, Sofi.', max_length=40, verbose_name='Nombre del Bot Comercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='system_prompt_extra',
            field=models.TextField(blank=True, default='', help_text='Instrucciones específicas de este cliente que se concatenan al system prompt de Nat. Útil para tono, productos prioritarios o restricciones por marca.', verbose_name='Instrucciones extra para el Bot Comercial'),
        ),
        migrations.AlterField(
            model_name='eventoia',
            name='tipo',
            field=models.CharField(choices=[('modulo_completado', 'Módulo completado'), ('checkpoint_evaluado', 'Checkpoint evaluado'), ('ia_agent_triggered', 'Agente IA activado'), ('rag_query_executed', 'Consulta RAG'), ('webhook_recibido', 'Webhook recibido'), ('intent_detectado', 'Intent detectado'), ('mensaje_enviado', 'Mensaje enviado')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='preguntas_realizadas',
            field=models.IntegerField(default=0, help_text='Preguntas de clarificación del agente PQRS (máximo 2 por ticket).', verbose_name='Preguntas de clarificación'),
        ),
    ]
