# Generated by Django 5.2.9 on 2026-06-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_productocomercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(help_text='Para qué sirve el producto', verbose_name='Descripción')),
                ('problema_que_resuelve', models.TextField(help_text='Síntomas o problemas del cultivo que este producto atiende. Ej: roya, manchas amarillas, deficiencia de nitrógeno, plagas de suelo. Mientras más descriptivo, mejor el match con la pregunta del agricultor.', verbose_name='Problemas que resuelve')),
                ('ingrediente_activo', models.CharField(blank=True, max_length=200, verbose_name='Ingrediente activo')),
                ('categoria', models.CharField(blank=True, help_text='Ej: fungicida, fertilizante foliar, bioestimulante, herbicida', max_length=100, verbose_name='Categoría')),
                ('cultivos_objetivo', models.CharField(blank=True, help_text='Ej: café, caña panelera, aguacate, maíz', max_length=300, verbose_name='Cultivos objetivo')),
                ('dosis', models.CharField(blank=True, help_text='Ej: 300-500g por 200L de agua', max_length=200, verbose_name='Dosis recomendada')),
                ('precio_cop', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio (COP)')),
                ('unidad', models.CharField(blank=True, help_text='Ej: 500g, 1L, bolsa x 25kg', max_length=50, verbose_name='Unidad de venta')),
                ('url_producto', models.URLField(blank=True, help_text='URL directa a la página de compra del producto', verbose_name='Link del producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto del catálogo',
                'verbose_name_plural': 'Catálogo de productos',
                'ordering': ['cliente', 'categoria', 'nombre'],
            },
        ),
        migrations.RenameIndex(
            model_name='productocomercial',
            new_name='core_produc_cliente_67a6bc_idx',
            old_name='core_produc_cliente_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='productocomercial',
            new_name='core_produc_nombre_576ee3_idx',
            old_name='core_produc_nombre_4c9b1e_idx',
        ),
        migrations.RenameIndex(
            model_name='productocomercial',
            new_name='core_produc_categor_04d104_idx',
            old_name='core_produc_categor_2f7a9c_idx',
        ),
        migrations.AddField(
            model_name='productocatalogo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_productos', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddConstraint(
            model_name='productocatalogo',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='uniq_producto_catalogo_cliente_nombre'),
        ),
    ]
