# Generated by Django 5.2.9 on 2026-06-03 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_cliente_numero_whatsapp_nat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_fin_suscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de suscripción'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de suscripción'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_proyecto',
            field=models.CharField(choices=[('cursos', 'Cursos eki'), ('gei', 'Inventario GEI'), ('nat', 'Agente Nat')], default='cursos', max_length=20, verbose_name='Tipo de producto contratado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Twilio Account SID propio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Twilio Auth Token propio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='twilio_whatsapp_from',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Twilio WhatsApp From propio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp_numero',
            field=models.CharField(blank=True, db_index=True, help_text='Número WhatsApp del cliente para multi-tenant futuro.', max_length=20, null=True, unique=True, verbose_name='WhatsApp propio del cliente'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta desde portal'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='solicitudsoporte',
            name='respuesta_portal',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta desde portal'),
        ),
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', '— Sin clasificar'), ('acceso', '🔑 Acceso (login, cédula, número)'), ('contenido', '📚 Contenido (módulo, video, examen)'), ('tecnico', '🛠️ Técnico (errores del sistema)'), ('duda_modulo', 'Duda de módulo'), ('problema_acceso', 'Problema de acceso'), ('solicitud_certificado', 'Solicitud de certificado'), ('consulta_calculo', 'Consulta de cálculo'), ('correccion_datos', 'Corrección de datos'), ('problema_tecnico', 'Problema técnico'), ('conversacion_escalada', 'Conversación escalada'), ('pregunta_sin_respuesta', 'Pregunta sin respuesta'), ('queja', 'Queja'), ('otro', '❓ Otro')], default='', help_text='Clasificación automática del agente PQRS (acceso, contenido, técnico, otro).', max_length=30, verbose_name='Categoría PQRS'),
        ),
    ]
