# Generated by Django 5.2.9 on 2026-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_enlace_formulario_validacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evaluacionnotagamificacion',
            new_name='core_evalua_estudia_8c5a7d_idx',
            old_name='core_evalno_est_fecha_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='content_sid_boton_listo',
            field=models.CharField(blank=True, default='', help_text='Content SID (HX…) con quick reply «Listo». Vacío = plantilla global continuar_modulo.', max_length=64, verbose_name='Plantilla botón Listo (Twilio)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modo_avance_modulo',
            field=models.CharField(choices=[('texto', 'Solo escribir listo / continuar'), ('boton', 'Solo botón WhatsApp (plantilla)'), ('ambos', 'Texto y botón')], default='texto', help_text='Texto = escribir listo (default). Botón = plantilla Twilio al cerrar entrega del módulo. No aplica en onboarding, PQRS ni conversación con agentes IA.', max_length=20, verbose_name='Avance entre módulos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='portal_productos',
            field=models.CharField(blank=True, default='', help_text='Opcional. Lista separada por coma: cursos, gei, nat, empleabilidad. Ej: cursos,empleabilidad o cursos,gei,nat. Vacío = solo el tipo principal.', max_length=100, verbose_name='Módulos del portal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_proyecto',
            field=models.CharField(choices=[('cursos', 'Cursos eki'), ('gei', 'Inventario GEI'), ('nat', 'Agente Nat')], default='cursos', help_text='Producto principal del contrato. Para combinar varios módulos en el portal, use «Módulos del portal».', max_length=20, verbose_name='Tipo de producto principal'),
        ),
    ]
