# Generated by Django 5.2.9 on 2026-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_segmento_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gei_factores_json',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides de factores de emisión (portal). Claves válidas = FACTORES en formulario.calculadora.', verbose_name='Factores GEI personalizados'),
        ),
    ]
