# Generated by Django 5.2.9 on 2026-06-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_curso_visible_en_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Avatar del estudiante (aula web y reportes).', null=True, upload_to='estudiantes/avatars/%Y/%m/', verbose_name='Foto de perfil'),
        ),
    ]
