# Generated by Django 5.2.9 on 2026-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_cupos_portal_primer_acceso'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bibliotecaconocimiento',
            new_name='core_biblio_cliente_6aa7dd_idx',
            old_name='core_biblio_cliente_cat_idx',
        ),
        migrations.AlterField(
            model_name='evaluacionnotagamificacion',
            name='tipo',
            field=models.CharField(choices=[('reto', 'Reto facilitadora'), ('pregunta_abierta', 'Pregunta abierta final'), ('manual', 'Manual (equipo)'), ('asistencia', 'Asistencia (aula docente)'), ('tarea_aula', 'Tarea aula web')], default='reto', max_length=30),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='contenido',
            field=models.TextField(blank=True, default='', help_text='Contenido del módulo completo (Legacy). Obligatorio solo sin microcontenidos; con pasos en Microcontenidos puede quedar vacío.'),
        ),
        migrations.AlterField(
            model_name='pasomodulo',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL pública del archivo (S3). Si usa «Subir archivo desde PC», se completa al Guardar. Debe verse un enlace https://… aquí; si queda vacío, el video no se enviará por WhatsApp.', max_length=1000),
        ),
    ]
