# Generated by Django 5.2.9 on 2026-07-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_paso_media_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextoagrosession',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud geocodificada (Open-Meteo u otra fuente)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contextoagrosession',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud geocodificada (Open-Meteo u otra fuente)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='contextoagrosession',
            name='vereda',
            field=models.CharField(blank=True, default='', help_text='Vereda, localidad o zona más exacta dentro del municipio', max_length=120),
        ),
    ]
