# Generated by Django 5.2.9 on 2026-07-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_contexto_agro_ubicacion_exacta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteEventoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contenido_enviado', 'Contenido enviado'), ('listo_recibido', 'Listo recibido'), ('evaluacion_respondida', 'Evaluación respondida'), ('recordatorio_enviado', 'Recordatorio enviado'), ('recordatorio_respondido', 'Recordatorio respondido'), ('media_entregada', 'Media entregada'), ('media_fallida', 'Media fallida'), ('modulo_iniciado', 'Módulo iniciado'), ('modulo_completado', 'Módulo completado')], db_index=True, max_length=40)),
                ('canal', models.CharField(db_index=True, default='whatsapp', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_aprendizaje', to='core.cliente')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_aprendizaje', to='core.estudiante')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='core.modulo')),
                ('paso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='core.pasomodulo')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_aprendizaje', to='core.seccionmodulo')),
            ],
            options={
                'verbose_name': 'Evento de aprendizaje',
                'verbose_name_plural': 'Eventos de aprendizaje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estudiante', 'created_at'], name='core_estudi_estudia_fd473a_idx'), models.Index(fields=['curso', 'tipo', 'created_at'], name='core_estudi_curso_i_191f2d_idx'), models.Index(fields=['modulo', 'tipo'], name='core_estudi_modulo__79963c_idx'), models.Index(fields=['cliente', 'tipo', 'created_at'], name='core_estudi_cliente_fbecb1_idx')],
            },
        ),
    ]
