# Generated by Django 5.2.9 on 2026-08-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_plantilla_verificacion_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='curso_destino',
            field=models.ForeignKey(blank=True, help_text='Al enviar, inscribe al estudiante en este curso (ProgresoEstudiante). Con «inicio de curso» = SÍ también reinicia Habeas. Con inicio = NO (10x): solo inscripción + plantilla de aviso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_curso', to='core.curso', verbose_name='Curso destino'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='es_campana_curso',
            field=models.BooleanField(default=False, help_text='SÍ: reinicia onboarding (Habeas → verificación → *listo*). Para cursos normales por WhatsApp. NO: solo aviso (ideal 10x / modo Clases). Si hay «Curso destino», igual se inscribe en Aprende sin tocar Habeas.', verbose_name='¿Es campaña de inicio de curso (WhatsApp + habeas)?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_whatsapp_nat',
            field=models.CharField(blank=True, default='', help_text='Número Twilio al que escribe el productor para hablar con Nat (solo dígitos, ej: 573001234567). Debe coincidir exactamente con el campo To del webhook; si no, el mensaje irá al bot educativo. Cada organización puede tener su propia línea. Distinto del número de campañas educativas y del BOT_COMERCIAL_CLIENTE_ID global.', max_length=20, verbose_name='Número WhatsApp Nat (línea comercial)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='wallpaper_aula_url',
            field=models.URLField(blank=True, help_text='Se completa sola al subir el archivo en admin. JPG/WebP ≤ 2 MB, ancho ≥ 1600px. Vacío = fondo eki por defecto.', max_length=500, verbose_name='URL del wallpaper (Aprende)'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='contenido',
            field=models.TextField(blank=True, default='', help_text='Texto legacy del módulo completo. Opcional si usa Clase, Estructura/Materiales o microcontenidos.'),
        ),
        migrations.AlterField(
            model_name='plantillacertificado',
            name='url_plantilla_imagen',
            field=models.URLField(blank=True, help_text='🔗 URL directa (PNG/JPG). Si también subes archivo, el archivo manda: al guardar se actualiza esta URL a la del archivo nuevo en S3.', max_length=500, null=True),
        ),
    ]
