# Generated by Django 5.2.9 on 2026-08-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_modulo_publicacion_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', '— Sin clasificar'), ('acceso', '🔑 Acceso (login, cédula, número)'), ('contenido', '📚 Contenido (módulo, video, examen)'), ('tecnico', '🛠️ Técnico (errores del sistema)'), ('organizacion', '🏢 Organización / cliente (no curso)'), ('duda_modulo', 'Duda de módulo'), ('problema_acceso', 'Problema de acceso'), ('solicitud_certificado', 'Solicitud de certificado'), ('consulta_calculo', 'Consulta de cálculo'), ('correccion_datos', 'Corrección de datos'), ('problema_tecnico', 'Problema técnico'), ('conversacion_escalada', 'Conversación escalada'), ('pregunta_sin_respuesta', 'Pregunta sin respuesta'), ('queja', 'Queja'), ('otro', '❓ Otro')], default='', help_text='Clasificación automática del agente PQRS (acceso, contenido, técnico, otro).', max_length=30, verbose_name='Categoría PQRS'),
        ),
        migrations.CreateModel(
            name='FaqOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text='Cómo la haría el estudiante (ej. ¿Cuándo pagan el bono?).', max_length=300, verbose_name='Pregunta')),
                ('respuesta', models.TextField(help_text='Texto que el agente envía por WhatsApp si hay coincidencia.', verbose_name='Respuesta')),
                ('palabras_clave', models.CharField(blank=True, default='', help_text='Opcional, separadas por coma (bono, pago, nómina). Mejoran el match.', max_length=400, verbose_name='Palabras clave')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs_organizacion', to='core.cliente', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'FAQ de organización',
                'verbose_name_plural': 'FAQ de organización (PQRS)',
                'ordering': ['orden', 'pregunta'],
            },
        ),
    ]
