# Generated by Django 5.2.9 on 2026-08-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_faq_organizacion_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='desactivar_llm_comercial',
            field=models.BooleanField(default=False, help_text='Si está marcado, eki.ia/Nat no llama al modelo de lenguaje: responde con catálogo, biblioteca/RAG y mensajes fijos (Plan B). Útil en incidente o costo. También existe el interruptor global EKI_IA_LLM_DISABLED en el servidor.', verbose_name='Kill switch LLM (eki.ia)'),
        ),
    ]
