# Generated by Django 5.2.9 on 2026-08-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_eki_ia_kill_switch_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='reto_guia_ia',
            field=models.TextField(blank=True, default='', help_text='Instrucciones y/o ejemplos para Claudia al cerrar ESTE módulo. Prioridad sobre la guía del curso. Ej: «Situación de caja semanal; una sola pregunta; que diga qué gasto cortaría primero».', verbose_name='Guía del reto (este módulo)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo_reto_ia',
            field=models.CharField(blank=True, choices=[('', 'Heredar / sin plantilla (solo guía de texto)'), ('situacion_decision', 'Situación + decisión práctica'), ('diagnostico', 'Diagnóstico (qué ve / qué verificaría)'), ('plan_accion', 'Plan de acción (qué haría esta semana)'), ('aplicacion_practica', 'Aplicación a su finca/trabajo'), ('reflexion', 'Reflexión breve (qué aprendió y cómo lo usa)')], default='', help_text='Solo importa si este módulo dispara checkpoint (facilitadora). Plantilla del formato de la pregunta. Vacío = sin plantilla fija.', max_length=32, verbose_name='Tipo de reto Claudia (este módulo)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preguntas_ejemplo_ia',
            field=models.TextField(blank=True, default='', help_text='Guía a Claudia (facilitadora) y a la pregunta de recuperación: tono, tipo de situación y 1–3 ejemplos. Una idea por línea. Si un módulo checkpoint tiene su propia guía/tipo de reto, esa manda y esta queda como complemento del curso.', verbose_name='Guía de retos / preguntas para IA (curso)'),
        ),
    ]
