# Generated by Django 5.2.9 on 2026-08-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_modulo_guia_tipo_reto_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='course_engine_tier',
            field=models.CharField(choices=[('economico', 'Economico (~20-30 s, sin Runway)'), ('estandar', 'Estandar (~25-35 s, 1 clip Runway)'), ('premium', 'Premium (~35-50 s, hasta 3 clips Runway)')], default='economico', help_text='Tier por defecto al generar micro-videos de modulos. Cada modulo puede override.', max_length=20, verbose_name='Tier video IA (default curso)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='course_engine_voice_id',
            field=models.CharField(blank=True, default='', help_text='ID de voz ElevenLabs (biblioteca o voz clonada del cliente). Ej. Wb1wmVQjMx9g2QSIOTPI. Si vacio, usa ELEVENLABS_VOICE_ID del entorno.', max_length=80, verbose_name='ElevenLabs Voice ID'),
        ),
        migrations.AddField(
            model_name='curso',
            name='course_engine_voice_label',
            field=models.CharField(blank=True, default='', help_text='Etiqueta ops: «Voz Maria», «Agronomo cliente Cenipalma», etc.', max_length=120, verbose_name='Nombre visible de la voz'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='course_engine_tier',
            field=models.CharField(blank=True, choices=[('', '— Heredar del curso —'), ('economico', 'Economico (~20-30 s, sin Runway)'), ('estandar', 'Estandar (~25-35 s, 1 clip Runway)'), ('premium', 'Premium (~35-50 s, hasta 3 clips Runway)')], default='', help_text='Vacío = usa tier del curso. Use estandar/premium solo en modulos hero.', max_length=20, verbose_name='Tier video IA (modulo)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='course_engine_voice_id',
            field=models.CharField(blank=True, default='', help_text='Override del curso. Util para voz clonada del cliente en un modulo concreto.', max_length=80, verbose_name='ElevenLabs Voice ID (modulo)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='course_engine_voice_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre visible de la voz (modulo)'),
        ),
        migrations.AlterField(
            model_name='archivomodulo',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('imagen', 'Imagen'), ('infografia', 'Infografía'), ('pdf', 'Documento PDF'), ('audio', 'Audio'), ('enlace_externo', 'Enlace externo')], max_length=20, verbose_name='Tipo de Archivo'),
        ),
        migrations.AlterField(
            model_name='archivomodulo',
            name='url_externa',
            field=models.URLField(blank=True, help_text='YouTube, PDF en la nube, etc. — o solo URL si el tipo es «Enlace externo» (formulario, Moodle, sitio web; se abre en otra pestaña).', max_length=500, null=True, verbose_name='O usar URL Externa'),
        ),
    ]
