# Generated by Django 5.2.9 on 2026-09-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_course_engine_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='course_engine_format',
            field=models.CharField(choices=[('solo_video', 'Solo video MP4 (1 paso WA)'), ('video_infografia', 'Video + infografía PNG (2 pasos)'), ('mixto_completo', 'Mixto completo: video + infografía + podcast (3 pasos)'), ('mixto_ligero', 'Ligero: video económico sin podcast ni PNG suelta')], default='video_infografia', help_text='Cómo se segmenta cada módulo al generar contenido IA (pasos WhatsApp).', max_length=24, verbose_name='Formato Course Engine (segmentación)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='course_engine_podcast_minutos',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 min'), (3, '3 min'), (4, '4 min')], default=2, help_text='Duración objetivo del podcast en formato mixto_completo.', verbose_name='Podcast (minutos)'),
        ),
    ]
