# Generated by Django 5.2.9 on 2026-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxCanalSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=30, unique=True)),
                ('modo', models.CharField(choices=[('menu', 'Menú'), ('nat', 'Nat / Agente IA'), ('cursos', 'Cursos')], default='menu', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión menú sandbox',
                'verbose_name_plural': 'Sesiones menú sandbox',
            },
        ),
        migrations.CreateModel(
            name='AlertaTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(db_index=True, max_length=80)),
                ('subtipo', models.CharField(default='cluster', max_length=80)),
                ('territory_id', models.CharField(db_index=True, max_length=32)),
                ('ventana_horas', models.PositiveIntegerField(default=72)),
                ('conteo', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('min_k', models.PositiveIntegerField(default=3)),
                ('estado', models.CharField(choices=[('detectada', 'Detectada'), ('validada', 'Validada'), ('comunicada', 'Comunicada'), ('accionada', 'Accionada'), ('cerrada', 'Cerrada')], db_index=True, default='detectada', max_length=20)),
                ('explicacion', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta territorial',
                'verbose_name_plural': 'Alertas territoriales',
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['territory_id', 'estado', '-score'], name='core_alerta_territo_fd6c70_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('org_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('territory_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('actor_pseudo', models.CharField(blank=True, default='', max_length=64)),
                ('session_or_trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_ids', models.JSONField(blank=True, default=list)),
                ('pii_class', models.CharField(default='internal', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lake_uri', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Evento outbox',
                'verbose_name_plural': 'Eventos outbox',
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['published_at', 'id'], name='core_evento_publish_c58b6b_idx'), models.Index(fields=['event_type', '-occurred_at'], name='core_evento_event_t_99aac5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SenalTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, help_text='Ej: salud.sintoma.diarrea', max_length=80)),
                ('territory_id', models.CharField(db_index=True, max_length=32)),
                ('org_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('confianza', models.FloatField(default=0.7)),
                ('fuente', models.CharField(default='manual', max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Señal territorial',
                'verbose_name_plural': 'Señales territoriales',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['territory_id', 'tipo', '-occurred_at'], name='core_senalt_territo_89188e_idx')],
            },
        ),
    ]
