# Generated by Django 5.2.9 on 2026-09-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_sandbox_agentes_memoria_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perfil_facilitador',
            field=models.CharField(choices=[('claudia', 'Claudia (facilitadora ABR eki)'), ('tecnicoagro', 'tecnicoagro (copiloto extensión AGROSAVIA)')], default='claudia', help_text='Quién plantea y evalúa los retos tras checkpoints. Claudia = default eki. tecnicoagro = copiloto técnico AGROSAVIA (mismo flujo, otro prompt). Los cursos pueden sobreescribir este valor.', max_length=20, verbose_name='Facilitador de retos (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='perfil_facilitador',
            field=models.CharField(blank=True, choices=[('', 'Heredar del cliente'), ('claudia', 'Claudia (facilitadora ABR eki)'), ('tecnicoagro', 'tecnicoagro (copiloto extensión AGROSAVIA)')], default='', help_text='Vacío = usa el facilitador del Cliente. Elija tecnicoagro solo en programas AGROSAVIA/agro; el resto suele quedar en Claudia.', max_length=20, verbose_name='Facilitador de retos (este curso)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preguntas_ejemplo_ia',
            field=models.TextField(blank=True, default='', help_text='Guía al facilitador (Claudia o tecnicoagro) y a la pregunta de recuperación: tono, tipo de situación y 1–3 ejemplos. Una idea por línea. Si un módulo checkpoint tiene su propia guía/tipo de reto, esa manda y esta queda como complemento del curso.', verbose_name='Guía de retos / preguntas para IA (curso)'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='publicado_wa',
            field=models.BooleanField(default=True, help_text='Activo = el bot puede enviar este módulo al avanzar. Pausado (desmarcado) = no se envía por WA; el estudiante se detiene en el último módulo activo anterior (no se borra el módulo). Los módulos nuevos en admin suelen empezar pausados hasta publicar.', verbose_name='Activo en WhatsApp'),
        ),
    ]
