# Generated by Django 5.2.9 on 2026-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_perfil_facilitador_tecnicoagro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteeventoaprendizaje',
            name='tipo',
            field=models.CharField(choices=[('contenido_enviado', 'Contenido enviado'), ('listo_recibido', 'Listo recibido'), ('evaluacion_respondida', 'Evaluación respondida'), ('recordatorio_enviado', 'Recordatorio enviado'), ('recordatorio_respondido', 'Recordatorio respondido'), ('media_entregada', 'Media entregada'), ('media_fallida', 'Media fallida'), ('modulo_iniciado', 'Módulo iniciado'), ('modulo_completado', 'Módulo completado'), ('reto_planteado', 'Reto planteado'), ('reto_respondido', 'Reto respondido')], db_index=True, max_length=40),
        ),
    ]
