# Generated by Django 5.2.9 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_eventos_reto_telemetria'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorag',
            name='uso_agente',
            field=models.CharField(
                choices=[
                    ('todos', 'Todos los agentes (compartido)'),
                    ('companero', 'Extra compañero (Darío / Carlos)'),
                    ('claudia', 'Extra Claudia (facilitadora)'),
                ],
                default='todos',
                help_text=(
                    'todos = Course Engine y todos los agentes edu. '
                    'companero/claudia = extra encima de todos, no oculta el material compartido.'
                ),
                max_length=20,
                verbose_name='Uso del documento',
            ),
        ),
    ]
