# Generated by Django 5.2.9 on 2026-09-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_video_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plan_linea_meta',
            field=models.CharField(blank=True, choices=[('curso_asesor', 'OP1 — 1 curso al mes + asesor (30 preguntas)'), ('dos_cursos', 'OP2 — 2 cursos al mes'), ('asesor_60', 'OP3 — asesor, 60 preguntas al mes')], default='', help_text='Lo que reciben sus estudiantes en la línea Meta. Vacío = sin plan (no abren cursos nuevos ni usan el asesor). Se puede cambiar por persona en «Sesiones menú sandbox».', max_length=20, verbose_name='Plan línea Meta'),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='aviso_pendiente',
            field=models.CharField(blank=True, default='', help_text='Línea de racha/insignia que va al inicio del próximo mensaje del día.', max_length=300),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='plan',
            field=models.CharField(blank=True, choices=[('curso_asesor', 'OP1 — 1 curso al mes + asesor (30 preguntas)'), ('dos_cursos', 'OP2 — 2 cursos al mes'), ('asesor_60', 'OP3 — asesor, 60 preguntas al mes')], default='', help_text='Vacío = usa el plan de su organización.', max_length=20, verbose_name='Plan (solo esta persona)'),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='preguntas_mes',
            field=models.PositiveIntegerField(default=0, verbose_name='Preguntas al asesor (mes)'),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='preguntas_mes_desde',
            field=models.DateField(blank=True, help_text='Primer día del mes al que corresponde el contador de preguntas.', null=True),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='racha_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Racha (días seguidos)'),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='racha_maxima',
            field=models.PositiveIntegerField(default=0, verbose_name='Récord de racha'),
        ),
        migrations.AddField(
            model_name='sandboxcanalsesion',
            name='racha_ultimo_dia',
            field=models.DateField(blank=True, null=True, verbose_name='Último día activo'),
        ),
    ]
