# Generated by Django 5.2.9 on 2026-09-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_plan_linea_y_racha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConocimientoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(choices=[('todos', 'Todos (Coach, Profe IA, Ventas)'), ('coach', 'Coach (Lina)'), ('ia_campo', 'Profe IA'), ('ventas', 'Ventas')], default='todos', max_length=16)),
                ('tipo', models.CharField(choices=[('conocimiento', 'Dato o respuesta validada'), ('instruccion', 'Regla de comportamiento')], default='conocimiento', max_length=16)),
                ('titulo', models.CharField(max_length=160, verbose_name='Tema')),
                ('contenido', models.TextField(help_text='Corto y concreto (máx. ~600 caracteres). Solo se usa si está Aprobado.', verbose_name='Lo que debe saber o hacer el agente')),
                ('estado', models.CharField(choices=[('sugerido', 'Sugerido (revisar)'), ('aprobado', 'Aprobado (lo usa el agente)'), ('descartado', 'Descartado')], default='aprobado', max_length=16)),
                ('origen', models.CharField(choices=[('manual', 'Equipo eki'), ('conversacion', 'Capturado de conversación')], default='manual', max_length=16)),
                ('pregunta_origen', models.TextField(blank=True, default='', verbose_name='Pregunta del usuario')),
                ('respuesta_origen', models.TextField(blank=True, default='', verbose_name='Respuesta que dio el agente')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conocimiento de agente',
                'verbose_name_plural': 'Entrenar agentes (Coach, Profe IA, Ventas)',
                'ordering': ['orden', '-actualizado_en'],
                'indexes': [models.Index(fields=['agente', 'estado'], name='core_conoci_agente_a17b7b_idx')],
            },
        ),
    ]
