# Generated by Django 5.2.9 on 2026-10-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_badges_racha'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestudiantes',
            name='plan_linea_meta',
            field=models.CharField(blank=True, choices=[('curso_asesor', 'OP1 — 1 curso al mes + asesor (30 preguntas)'), ('dos_cursos', 'OP2 — 2 cursos al mes'), ('asesor_60', 'OP3 — asesor, 60 preguntas al mes')], default='', help_text='Plan de las personas de este grupo. Vacío = usan el plan del cliente. Así un mismo cliente puede tener un grupo en OP1 y otro en OP2. Si alguien está en varios grupos con plan, gana el grupo creado de último.', max_length=20, verbose_name='Plan línea Meta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plan_linea_meta',
            field=models.CharField(blank=True, choices=[('curso_asesor', 'OP1 — 1 curso al mes + asesor (30 preguntas)'), ('dos_cursos', 'OP2 — 2 cursos al mes'), ('asesor_60', 'OP3 — asesor, 60 preguntas al mes')], default='', help_text='Plan de quienes no estén en un grupo con plan propio. Vacío = sin plan (no abren cursos nuevos ni usan el asesor). Un grupo puede llevar OP1 y otro OP2. Una persona se cambia en «Sesiones menú sandbox».', max_length=20, verbose_name='Plan línea Meta'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='catalogo_menu',
            field=models.BooleanField(default=False, help_text='Sin cliente y marcado: sale en Formación. Al crear un curso general queda marcado. WhatsApp muestra hasta 10 por carrusel; si hay más, manda otro a continuación. Desmárquelo para ocultarlo.', verbose_name='Catálogo general del menú'),
        ),
        migrations.AlterField(
            model_name='sandboxcanalsesion',
            name='plan',
            field=models.CharField(blank=True, choices=[('curso_asesor', 'OP1 — 1 curso al mes + asesor (30 preguntas)'), ('dos_cursos', 'OP2 — 2 cursos al mes'), ('asesor_60', 'OP3 — asesor, 60 preguntas al mes')], default='', help_text='Vacío = usa el plan de su grupo y, si el grupo no tiene, el de su organización.', max_length=20, verbose_name='Plan (solo esta persona)'),
        ),
    ]
