# Generated by Django 5.2.9 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_plantilla_meta_tipos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=10)),
                ('external_id', models.CharField(max_length=128)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canal', 'external_id'), name='uniq_webhook_evento')],
            },
        ),
    ]
