# Generated by Django 5.2.9 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_webhook_evento_procesado'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'webhook fallido',
                'verbose_name_plural': 'webhooks fallidos',
            },
        ),
    ]
