# Generated by Django 5.2.9 on 2026-10-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_whatsapplog_error_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWebhookEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(blank=True, default='', max_length=32)),
                ('payload_raw', models.JSONField(blank=True, default=dict)),
                ('firma_ok', models.BooleanField(default=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('respondido', 'Respondido'), ('sin_plan', 'Sin plan'), ('ignorado_twilio', 'Twilio hacia la línea Meta'), ('ignorado', 'Ignorado'), ('error', 'Error'), ('tipo_no_soportado', 'Tipo no soportado'), ('recibido', 'Recibido')], default='', max_length=32)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('estado_chat_antes', models.CharField(blank=True, default='', max_length=50)),
                ('plan_efectivo', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Evento webhook Meta',
                'verbose_name_plural': 'Eventos webhook Meta',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
