# Generated by Django 5.2.9 on 2026-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_meta_webhook_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='area_unidad_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para A2 cuando exista práctica adoptada. No se publica como causa.', max_digits=10, null=True, verbose_name='Área de la unidad (ha)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='consentimiento_impacto',
            field=models.BooleanField(default=False, help_text='Distinto del habeas operativo. Hace falta para incluir a esta persona en Impacto.', verbose_name='Consentimiento para reportes de impacto'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='consentimiento_impacto_acudiente',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Acudiente (menores)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='consentimiento_impacto_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del consentimiento de impacto'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pdet',
            field=models.BooleanField(blank=True, help_text='Corte de impacto. Vacío = desconocido. No cambia el chat.', null=True, verbose_name='Municipio PDET'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='rural_disperso',
            field=models.BooleanField(blank=True, help_text='Corte de impacto. Vacío = desconocido. No cambia el chat.', null=True, verbose_name='Rural disperso'),
        ),
    ]
