# Generated by Django 5.2.9 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0095_alter_contextoagrosession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoIA',
            fields=[
            ],
            options={
                'verbose_name': 'Evento IA',
                'verbose_name_plural': 'Eventos IA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.eventoia',),
        ),
        migrations.CreateModel(
            name='MetaMetricaEmpresa',
            fields=[
            ],
            options={
                'verbose_name': 'Meta métrica empresa',
                'verbose_name_plural': 'Metas métricas por empresa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.metametricaempresa',),
        ),
    ]
