# Generated by Django 5.2.9 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0095_alter_contextoagrosession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRAG',
            fields=[
            ],
            options={
                'verbose_name': 'Documento RAG',
                'verbose_name_plural': 'Documentos RAG (Base de Conocimiento IA)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.documentorag',),
        ),
    ]
