# Generated by Django 5.2.9 on 2025-12-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cuerpo_plantilla_cuerpo_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviolog',
            name='respuesta_api',
            field=models.TextField(blank=True, help_text='Respuesta del servidor', null=True),
        ),
    ]
