# Generated by Django 5.2.9 on 2025-12-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_linea_campana_canal_envio_campana_fecha_programada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('mensaje_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('estado', models.CharField(default='PENDING', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campana',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
    ]
