# Generated by Django 5.2.9 on 2026-03-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plantilla_tiene_imagen_plantilla_url_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoEmpleabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('vacantes_activas', models.BooleanField(default=True)),
                ('codigo_secreto', models.CharField(help_text='Código que el estudiante debe enviar al encontrar la empresa.', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aliado de Empleabilidad',
                'verbose_name_plural': 'Aliados de Empleabilidad',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('dias_espera_entre_modulos', models.IntegerField(default=0, help_text='Días de espera entre módulos (0 = sin espera, 7 = semanal).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='LogroEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('graduacion', 'Graduación'), ('empleabilidad', 'Empleabilidad'), ('modulo', 'Módulo Completado'), ('curso', 'Curso Completado')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aliado', models.ForeignKey(blank=True, help_text='Empresa aliada vinculada al logro (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aliadoempleabilidad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Logro del Estudiante',
                'verbose_name_plural': 'Logros de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_abiertas', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Pregunta Abierta',
                'verbose_name_plural': 'Preguntas Abiertas',
                'ordering': ['modulo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultimo_avance', models.DateTimeField(blank=True, help_text='Fecha en que el estudiante completó el último módulo.', null=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En Curso'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado')], default='en_curso', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.estudiante')),
                ('modulo_actual', models.ForeignKey(blank=True, help_text='Módulo en el que se encuentra actualmente el estudiante.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulo')),
            ],
            options={
                'verbose_name': 'Progreso del Estudiante',
                'verbose_name_plural': 'Progresos de Estudiantes',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación asignada por la facilitadora (ej. 0.00 – 5.00).', max_digits=5, null=True)),
                ('comentario_facilitador', models.TextField(blank=True, help_text='Retroalimentación de la facilitadora.')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('calificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_abiertas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_abiertas', to='core.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.preguntaabierta')),
            ],
            options={
                'verbose_name': 'Respuesta Abierta',
                'verbose_name_plural': 'Respuestas Abiertas',
                'unique_together': {('pregunta', 'estudiante')},
            },
        ),
    ]
