# Generated by Django 5.2.9 on 2026-09-03 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0141_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('nombre_escenario', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('presentacion', models.CharField(blank=True, default='', max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidad_venta', models.CharField(default='unidad', max_length=40)),
                ('ubicacion_actual', models.CharField(blank=True, default='', max_length=200)),
                ('mercado_objetivo', models.CharField(blank=True, default='', max_length=200)),
                ('alcance', models.CharField(choices=[('local', 'Local'), ('departamental', 'Departamental'), ('nacional', 'Nacional'), ('exportacion', 'Exportación')], default='local', max_length=20)),
                ('segmentos_cliente', models.JSONField(blank=True, default=list)),
                ('ticket_mensual_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('capacidad_mensual_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tam', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('sam', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('som_conservador', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('som_base', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('som_ambicioso', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('confianza_estimacion', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('nota_confianza', models.TextField(blank=True, default='')),
                ('trazabilidad', models.JSONField(blank=True, default=dict)),
                ('gtm', models.JSONField(blank=True, default=dict)),
                ('extraccion', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_mercado', to='core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_mercado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escenario de mercado',
                'verbose_name_plural': 'Escenarios de mercado',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
