# Generated by Django 5.2.9 on 2026-06-29 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0001_tareas_aula'),
        ('core', '0114_estudiante_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEstudianteAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='aprende/documentos/%Y/%m/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_estudiantes_aula', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_aula', to='core.estudiante')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_estudiantes_aula', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Documento del estudiante (aula)',
                'verbose_name_plural': 'Documentos del estudiante (aula)',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
