# Generated by Django 5.2.9 on 2026-07-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0003_asistencia_aula'),
        ('core', '0127_estudiante_documento_latam'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoQuizModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(blank=True, default=dict)),
                ('correctas', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quiz_aula', to='core.estudiante')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quiz_aula', to='core.modulo')),
            ],
            options={
                'verbose_name': 'Intento quiz (aula)',
                'verbose_name_plural': 'Intentos quiz (aula)',
                'ordering': ['-fecha'],
                'unique_together': {('estudiante', 'modulo')},
            },
        ),
    ]
