# Generated by Django 5.2.9 on 2026-07-31 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0004_intento_quiz_modulo'),
        ('core', '0127_estudiante_documento_latam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAccesoAprende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_acceso_aprende', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Código acceso Aprende',
                'verbose_name_plural': 'Códigos acceso Aprende',
            },
        ),
    ]
