# Generated by Django 5.2.9 on 2026-08-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0005_codigo_acceso_aprende'),
        ('core', '0131_paso_media_wa_apto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialAprendeEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_aprende', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Credencial Aprende',
                'verbose_name_plural': 'Credenciales Aprende',
            },
        ),
    ]
