# Generated by Django 5.2.9 on 2026-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprende', '0006_credencial_aprende_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='fecha_respuesta_estudiante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='respuesta_estudiante',
            field=models.TextField(blank=True, help_text='Comentario del estudiante después de ver la calificación del profesor.'),
        ),
    ]
