# Generated by Django 5.2.9 on 2026-06-29 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0115_curso_visible_en_studio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreadorStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_publico', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=False, help_text='Revisión eki antes de publicar en catálogo.')),
                ('wompi_recipient_id', models.CharField(blank=True, default='', help_text='ID de beneficiario Wompi para split de pagos (futuro).', max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creador_studio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creador Studio',
                'verbose_name_plural': 'Creadores Studio',
            },
        ),
        migrations.CreateModel(
            name='CuentaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(blank=True, default='', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_aula', to='core.estudiante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_aula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta aula / Studio',
                'verbose_name_plural': 'Cuentas aula / Studio',
            },
        ),
        migrations.CreateModel(
            name='PublicacionStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cop', models.DecimalField(decimal_places=0, default=0, help_text='0 = gratuito. Monto en pesos colombianos.', max_digits=12)),
                ('destacado', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='studio.creadorstudio')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_studio', to='core.curso')),
            ],
            options={
                'verbose_name': 'Publicación Studio',
                'verbose_name_plural': 'Publicaciones Studio',
            },
        ),
        migrations.CreateModel(
            name='AccesoCursoPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('monto_cop', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('wompi_referencia', models.CharField(db_index=True, max_length=64, unique=True)),
                ('wompi_transaccion_id', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_pagados', to='core.curso')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_curso', to='studio.cuentaaula')),
            ],
            options={
                'verbose_name': 'Acceso curso pagado',
                'verbose_name_plural': 'Accesos curso pagados',
                'indexes': [models.Index(fields=['cuenta', 'curso', 'estado'], name='studio_acce_cuenta__1a5098_idx')],
            },
        ),
    ]
