# Generated by Django 5.2.9 on 2026-07-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_paso_media_url_max_length'),
        ('studio', '0001_cuentas_creadores_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='studio.cuentaaula')),
            ],
            options={
                'verbose_name': 'Carrito Studio',
                'verbose_name_plural': 'Carritos Studio',
            },
        ),
        migrations.CreateModel(
            name='OrdenStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('monto_cop', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('wompi_referencia', models.CharField(db_index=True, max_length=64, unique=True)),
                ('wompi_transaccion_id', models.CharField(blank=True, default='', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='studio.cuentaaula')),
            ],
            options={
                'verbose_name': 'Orden Studio',
                'verbose_name_plural': 'Órdenes Studio',
            },
        ),
        migrations.CreateModel(
            name='OrdenItemStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cop', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items_studio', to='core.curso')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='studio.publicacionstudio')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studio.ordenstudio')),
            ],
            options={
                'verbose_name': 'Ítem orden Studio',
                'verbose_name_plural': 'Ítems orden Studio',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studio.carritostudio')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='studio.publicacionstudio')),
            ],
            options={
                'verbose_name': 'Ítem carrito Studio',
                'verbose_name_plural': 'Ítems carrito Studio',
                'constraints': [models.UniqueConstraint(fields=('carrito', 'publicacion'), name='uniq_carrito_publicacion_studio')],
            },
        ),
    ]
