# Generated by Django 5.2.9 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_carrito_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creadorstudio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Perfil listo para publicar en catálogo.'),
        ),
    ]
