# Generated by Django 5.2.9 on 2026-09-02 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0141_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoMargen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('cantidad_producida', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unidad', models.CharField(default='unidades', max_length=40)),
                ('materias_primas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('empaque', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costos_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('margen_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_sugerido_25', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('recomendaciones', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_margen', to='core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos_margen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo de margen',
                'verbose_name_plural': 'Cálculos de margen',
                'ordering': ['-creado_en'],
            },
        ),
    ]
