from django.urls import path

from . import views

urlpatterns = [
    path('', views.inicio, name='aprende_inicio'),
    path('manifest.webmanifest', views.manifest_webmanifest, name='aprende_manifest'),
    path('sw.js', views.service_worker, name='aprende_sw'),
    path('handoff/', views.handoff_desde_studio, name='aprende_handoff'),
    path('estudiante/login/', views.estudiante_login, name='aprende_estudiante_login'),
    path('estudiante/clave/', views.estudiante_crear_clave, name='aprende_estudiante_clave'),
    path('estudiante/logout/', views.estudiante_logout, name='aprende_estudiante_logout'),
    path('estudiante/', views.estudiante_cursos, name='aprende_estudiante_cursos'),
    path('estudiante/tareas/', views.estudiante_tareas, name='aprende_estudiante_tareas'),
    path('estudiante/curso/<int:curso_id>/', views.estudiante_curso, name='aprende_estudiante_curso'),
    path('estudiante/curso/<int:curso_id>/tareas/', views.estudiante_curso_tareas, name='aprende_estudiante_curso_tareas'),
    path('estudiante/curso/<int:curso_id>/ranking/', views.estudiante_curso_ranking, name='aprende_estudiante_curso_ranking'),
    path('estudiante/tarea/<int:tarea_id>/', views.estudiante_tarea, name='aprende_estudiante_tarea'),
    path('estudiante/modulo/<int:modulo_id>/', views.estudiante_modulo, name='aprende_estudiante_modulo'),
    path('estudiante/biblioteca/', views.estudiante_biblioteca, name='aprende_estudiante_biblioteca'),
    path('estudiante/perfil/', views.estudiante_perfil, name='aprende_estudiante_perfil'),
    path('profesor/login/', views.profesor_login, name='aprende_profesor_login'),
    path('profesor/logout/', views.profesor_logout, name='aprende_profesor_logout'),
    path('profesor/', views.profesor_cursos, name='aprende_profesor_cursos'),
    path('profesor/curso/<int:curso_id>/', views.profesor_curso, name='aprende_profesor_curso'),
    path('profesor/curso/<int:curso_id>/modulo/nuevo/', views.profesor_modulo_nuevo, name='aprende_profesor_modulo_nuevo'),
    path('profesor/curso/<int:curso_id>/tarea/nueva/', views.profesor_tarea_nueva, name='aprende_profesor_tarea_nueva'),
    path('profesor/tarea/<int:tarea_id>/editar/', views.profesor_tarea_editar, name='aprende_profesor_tarea_editar'),
    path('profesor/tarea/<int:tarea_id>/eliminar/', views.profesor_tarea_eliminar, name='aprende_profesor_tarea_eliminar'),
    path('profesor/tarea/<int:tarea_id>/entregas/', views.profesor_tarea_entregas, name='aprende_profesor_tarea_entregas'),
    path('profesor/curso/<int:curso_id>/asistencia/', views.profesor_curso_asistencia, name='aprende_profesor_asistencia'),
    path('profesor/curso/<int:curso_id>/asistencia/excel/', views.profesor_curso_asistencia_excel, name='aprende_profesor_asistencia_excel'),
    path('profesor/curso/<int:curso_id>/calificaciones/', views.profesor_curso_calificaciones, name='aprende_profesor_calificaciones'),
    path('profesor/curso/<int:curso_id>/ranking/', views.profesor_curso_ranking, name='aprende_profesor_ranking'),
    path('profesor/modulo/<int:modulo_id>/', views.profesor_modulo_editar, name='aprende_profesor_modulo_editar'),
    path(
        'profesor/modulo/<int:modulo_id>/vista-estudiante/',
        views.profesor_modulo_vista_estudiante,
        name='aprende_profesor_modulo_vista_estudiante',
    ),
]
