# Generated by Django 5.2.9 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0095_alter_contextoagrosession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaB2B',
            fields=[
            ],
            options={
                'verbose_name': 'Campaña B2B',
                'verbose_name_plural': 'Campañas B2B',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.campanab2b',),
        ),
        migrations.CreateModel(
            name='ContextoAgroSession',
            fields=[
            ],
            options={
                'verbose_name': 'Contexto agronómico (Nat)',
                'verbose_name_plural': 'Contextos agronómicos (Nat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.contextoagrosession',),
        ),
        migrations.CreateModel(
            name='ConversacionRAGCandidata',
            fields=[
            ],
            options={
                'verbose_name': 'Candidata RAG (HITL)',
                'verbose_name_plural': 'Candidatas RAG (HITL)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.conversacionragcandidata',),
        ),
        migrations.CreateModel(
            name='DocumentoRAGComercial',
            fields=[
            ],
            options={
                'verbose_name': 'Documento RAG Comercial',
                'verbose_name_plural': 'Documentos RAG Comercial',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.documentoragcomercial',),
        ),
        migrations.CreateModel(
            name='MetaMetricaNati',
            fields=[
            ],
            options={
                'verbose_name': 'Meta métrica Nat',
                'verbose_name_plural': 'Metas métricas Nat',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.metametricanati',),
        ),
        migrations.CreateModel(
            name='ProspectoB2B',
            fields=[
            ],
            options={
                'verbose_name': 'Prospecto B2B',
                'verbose_name_plural': 'Prospectos B2B (Leads)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.prospectob2b',),
        ),
    ]
