# Generated by Django 5.2.9 on 2026-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0095_alter_contextoagrosession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliadoEmpleabilidad',
            fields=[
            ],
            options={
                'verbose_name': 'Aliado de Empleabilidad',
                'verbose_name_plural': 'Aliados de Empleabilidad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.aliadoempleabilidad',),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': '🔐 Sistema → Auditoría',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.auditlog',),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.badge',),
        ),
        migrations.CreateModel(
            name='BadgeEstudiante',
            fields=[
            ],
            options={
                'verbose_name': 'Badge de Estudiante',
                'verbose_name_plural': 'Badges de Estudiantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.badgeestudiante',),
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Canjes de Recompensas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.canjerecompensa',),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
            ],
            options={
                'verbose_name': '📜 Certificado',
                'verbose_name_plural': '📜 Certificados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.certificado',),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.examen',),
        ),
        migrations.CreateModel(
            name='MisionEmpleabilidad',
            fields=[
            ],
            options={
                'verbose_name': 'Misión de Empleabilidad',
                'verbose_name_plural': 'Misiones de Empleabilidad',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.misionempleabilidad',),
        ),
        migrations.CreateModel(
            name='PerfilGamificacion',
            fields=[
            ],
            options={
                'verbose_name': 'Perfil de Gamificación',
                'verbose_name_plural': 'Perfiles de Gamificación',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.perfilgamificacion',),
        ),
        migrations.CreateModel(
            name='PlantillaCertificado',
            fields=[
            ],
            options={
                'verbose_name': '🎨 Plantilla de Certificado',
                'verbose_name_plural': '🎨 Plantillas de Certificados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.plantillacertificado',),
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS (Peticiones/Quejas/Reclamos/Sugerencias)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pqrs',),
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaFinalCurso',
            fields=[
            ],
            options={
                'verbose_name': 'Pregunta Abierta Final',
                'verbose_name_plural': 'Preguntas Abiertas Finales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.preguntaabiertafinalcurso',),
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Examen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.preguntaexamen',),
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.recompensa',),
        ),
        migrations.CreateModel(
            name='RespuestaAbiertaFinal',
            fields=[
            ],
            options={
                'verbose_name': 'Respuesta Abierta Final',
                'verbose_name_plural': 'Respuestas Abiertas Finales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.respuestaabiertafinal',),
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.resultadoexamen',),
        ),
        migrations.CreateModel(
            name='TransaccionPuntos',
            fields=[
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'verbose_name_plural': 'Transacciones de Puntos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaccionpuntos',),
        ),
    ]
