# Generated by Django 5.2.9 on 2026-04-26 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0077_alter_curso_dias_espera_entre_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaGEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(blank=True, default='', max_length=200)),
                ('area_ha', models.FloatField(blank=True, null=True, verbose_name='Área (ha)')),
                ('num_plantas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de plantas')),
                ('fertilizante_kg', models.FloatField(blank=True, null=True, verbose_name='Fertilizante (kg)')),
                ('concentracion_n_pct', models.FloatField(blank=True, null=True, verbose_name='Concentración de N (%)')),
                ('tipo_combustible', models.CharField(blank=True, choices=[('', '—'), ('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('glp', 'GLP'), ('otro', 'Otro / no aplica')], default='', max_length=20)),
                ('combustible_gal', models.FloatField(blank=True, null=True, verbose_name='Combustible (gal)')),
                ('energia_kwh', models.FloatField(blank=True, null=True, verbose_name='Energía (kWh)')),
                ('residuos_ton', models.FloatField(blank=True, null=True, verbose_name='Residuos (t)')),
                ('manejo_residuos', models.CharField(blank=True, choices=[('', '—'), ('compost', 'Compost o enterrado en finca'), ('externo', 'Entrega a tercero / recolección'), ('quemado', 'Quema en campo (no recomendado)'), ('otro', 'Otra forma / no aplica')], default='', max_length=30)),
                ('produccion_kg', models.FloatField(blank=True, null=True, verbose_name='Producción (kg)')),
                ('tiene_bosque', models.BooleanField(blank=True, null=True, verbose_name='¿Tiene bosque o setos?')),
                ('area_bosque_ha', models.FloatField(blank=True, null=True, verbose_name='Área de bosque o cobertura (ha)')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_gei', to='core.cliente')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_gei', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_gei', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Ficha GEI',
                'verbose_name_plural': 'Fichas GEI',
                'ordering': ('-fecha_update',),
            },
        ),
        migrations.CreateModel(
            name='TipoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas internas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_formulario', to='core.curso', verbose_name='Curso')),
                ('modulo', models.ForeignKey(help_text='Módulo que al completar dispara el formulario (p. ej. módulo 4).', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_formulario', to='core.modulo', verbose_name='Módulo disparador')),
            ],
            options={
                'verbose_name': 'Tipo de formulario',
                'verbose_name_plural': 'Tipos de formulario',
                'ordering': ('curso', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='SesionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_actual', models.PositiveIntegerField(default=0, verbose_name='Paso (índice 0 = primera pregunta)')),
                ('ficha_destino_id', models.PositiveIntegerField(default=0, editable=False, help_text='Coincide con ficha_id (compatibilidad).')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('reintentos_paso', models.PositiveSmallIntegerField(default=0, verbose_name='Reintentos en el paso actual')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_formulario', to='core.estudiante')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='formulario.fichagei', verbose_name='Ficha destino')),
                ('modulo_siguiente', models.ForeignKey(blank=True, help_text='Tras finalizar el formulario, se avanza el curso a este módulo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_formulario_que', to='core.modulo')),
                ('progreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_formulario_gei', to='core.progresoestudiante')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='formulario.tipoformulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Sesión de formulario',
                'verbose_name_plural': 'Sesiones de formulario',
                'ordering': ('-fecha_update',),
                'indexes': [models.Index(fields=['estudiante', 'completado', 'fecha_update'], name='formulario__estudia_b4bdd2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlujoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('campo_destino', models.CharField(help_text='Nombre del atributo, por ejemplo: fertilizante_kg', max_length=80, verbose_name='Campo destino en FichaGEI')),
                ('pregunta_texto', models.TextField(verbose_name='Texto de la pregunta (usted, sin tecnicismos)')),
                ('tipo_dato', models.CharField(choices=[('float', 'Número decimal'), ('bool', 'Sí o no'), ('choice', 'Lista de opciones'), ('text', 'Texto breve')], default='float', max_length=20, verbose_name='Tipo de dato')),
                ('rango_min', models.FloatField(blank=True, null=True, verbose_name='Mínimo (si aplica)')),
                ('rango_max', models.FloatField(blank=True, null=True, verbose_name='Máximo (si aplica)')),
                ('unidad_parseo', models.CharField(blank=True, default='', max_length=40, verbose_name='Unidad esperada (parseo con IA)')),
                ('opciones_choice', models.TextField(blank=True, default='', help_text='Para tipo «Lista de opciones»: valores separados por | (ej. diésel|gasolina|GLP).', verbose_name='Opciones (choice)')),
                ('usar_llm_parseo', models.BooleanField(default=False, verbose_name='Usar IA para leer el número o cantidad en lenguaje natural')),
                ('es_opcional', models.BooleanField(default=False, verbose_name='Puede omitirse (OMITIR)')),
                ('texto_reintento', models.TextField(blank=True, default='', verbose_name='Mensaje si la respuesta no es válida')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujo_pasos', to='formulario.tipoformulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Paso del flujo',
                'verbose_name_plural': 'Pasos del flujo',
                'ordering': ('formulario', 'orden'),
                'unique_together': {('formulario', 'orden')},
            },
        ),
    ]
