# Generated by Django 5.2.9 on 2026-04-26 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_curso_dias_espera_entre_modulos'),
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoformulario',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los clientes. Específico = solo para ese cliente (tiene prioridad sobre el global).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_formulario', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
