# Generated by Django 5.2.9 on 2026-04-28 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_tipoformulario_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoGEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_fertilizante_kg', models.FloatField(blank=True, null=True, verbose_name='Em. fertilizante (kg CO₂e)')),
                ('em_combustible_kg', models.FloatField(blank=True, null=True, verbose_name='Em. combustible (kg CO₂e)')),
                ('em_energia_kg', models.FloatField(blank=True, null=True, verbose_name='Em. energía (kg CO₂e)')),
                ('em_residuos_kg', models.FloatField(blank=True, null=True, verbose_name='Em. residuos (kg CO₂e)')),
                ('em_total_kg', models.FloatField(blank=True, null=True, verbose_name='Emisiones totales (kg CO₂e)')),
                ('rem_bosque_kg', models.FloatField(blank=True, null=True, verbose_name='Remoción bosque (kg CO₂e)')),
                ('balance_neto_tco2e', models.FloatField(blank=True, null=True, verbose_name='Balance neto (t CO₂e/año)')),
                ('intensidad_kg_co2e_por_kg', models.FloatField(blank=True, null=True, verbose_name='Intensidad (kg CO₂e / kg producto)')),
                ('evaluacion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('mejorable', 'Mejorable')], max_length=20, null=True, verbose_name='Evaluación (benchmark café)')),
                ('completitud_calculo_pct', models.IntegerField(default=0, verbose_name='Completitud del cálculo (%)')),
                ('campos_faltantes', models.JSONField(blank=True, default=list, verbose_name='Campos faltantes')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, verbose_name='Último cálculo')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='formulario.fichagei', verbose_name='Ficha GEI')),
            ],
            options={
                'verbose_name': 'Resultado GEI',
                'verbose_name_plural': 'Resultados GEI',
            },
        ),
    ]
