from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.portal_login, name='portal_login'),
    path('logout/', views.portal_logout, name='portal_logout'),
    path('dashboard/', views.dashboard, name='portal_dashboard'),
    path('metricas/', views.metricas_empresa, name='portal_metricas'),
    path('gamificacion/', views.portal_gamificacion, name='portal_gamificacion'),
    path('empleabilidad/', views.portal_empleabilidad, name='portal_empleabilidad'),
    path('cobertura/', views.portal_cobertura, name='portal_cobertura'),
    path('cobertura/datos.json', views.portal_cobertura_api, name='portal_cobertura_api'),
    path('cobertura/departamentos.geojson', views.portal_cobertura_geojson, name='portal_cobertura_geojson'),
    path('cobertura/municipios.geojson', views.portal_cobertura_municipios_geojson, name='portal_cobertura_municipios_geojson'),
    path('gei/', views.portal_gei, name='portal_gei'),
    path('gei/exportar/', views.portal_gei_exportar, name='portal_gei_exportar'),
    path('gei/<int:ficha_id>/', views.portal_gei_detalle, name='portal_gei_detalle'),
    path('gei/formularios/', views.portal_gei_formularios, name='portal_gei_formularios'),
    path('gei/formularios/<int:formulario_id>/', views.portal_gei_formulario_editar, name='portal_gei_formulario_editar'),
    path('nat/', views.portal_nat, name='portal_nat'),
    path('nat/documentos/', views.portal_nat_documentos, name='portal_nat_documentos'),
    path('campanas/', views.campanas_lista, name='portal_campanas'),
    path('campanas/<int:campana_id>/', views.campana_detalle, name='portal_campana_detalle'),
    path('conversaciones/', views.portal_conversaciones, name='portal_conversaciones'),
    path('estudiantes/', views.estudiantes, name='portal_estudiantes'),
    path('estudiantes/exportar/', views.exportar_estudiantes_excel, name='portal_exportar_estudiantes'),
    path('estudiantes/exportar/avance/', views.exportar_avance_excel, name='portal_exportar_avance'),
    path('reportes/', views.portal_reportes, name='portal_reportes'),
    path('estudiantes/<int:estudiante_id>/', views.estudiante_detalle, name='portal_estudiante_detalle'),
    path('cursos/', views.cursos_lista, name='portal_cursos'),
    path('cursos/<int:curso_id>/flujo/', views.portal_curso_flujo, name='portal_curso_flujo'),
    path('certificados/', views.portal_certificados, name='portal_certificados'),
    path('pqrs/', views.pqrs_lista, name='portal_pqrs'),
    path('pqrs/<int:pqrs_id>/', views.pqrs_detalle, name='portal_pqrs_detalle'),
    path('perfil/', views.perfil_organizacion, name='portal_perfil'),
    path('suscripcion-vencida/', views.suscripcion_vencida, name='portal_vencida'),
]
